[project]
name = "cobol-ast-service"
version = "5.7.5"
description = "COBOL to Python Transpiler API"
requires-python = ">=3.12"

dependencies = []

[build-system]
requires = ["hatchling>=1.18.0"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["api"]
