/**
 * ALTER PROCEDURE Handler - v6.1.0
 * Gestion des edge cases ALTER, GOTO dynamiques, DEPENDING ON
 */

export interface AlterStatement {
  line: number;
  originalTarget: string;
  newTarget: string;
  context: string;
}

export interface GotoDynamic {
  line: number;
  targets: string[];
  dependingOn?: string;
}

export interface AlterAnalysis {
  alterStatements: AlterStatement[];
  dynamicGotos: GotoDynamic[];
  riskLevel: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  stateVariables: string[];
  pythonStateMachine: string;
  warnings: string[];
}

/**
 * Detect ALTER statements in COBOL code
 */
export function detectAlterStatements(cobolCode: string): AlterStatement[] {
  const alters: AlterStatement[] = [];
  const lines = cobolCode.split('\n');
  
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    // ALTER paragraph-1 TO PROCEED TO paragraph-2
    const alterMatch = line.match(/ALTER\s+([\w-]+)\s+TO\s+(?:PROCEED\s+TO\s+)?([\w-]+)/i);
    
    if (alterMatch) {
      alters.push({
        line: i + 1,
        originalTarget: alterMatch[1],
        newTarget: alterMatch[2],
        context: lines.slice(Math.max(0, i - 2), i + 3).join('\n')
      });
    }
  }
  
  return alters;
}

/**
 * Detect dynamic GOTO statements (GOTO DEPENDING ON)
 */
export function detectDynamicGotos(cobolCode: string): GotoDynamic[] {
  const gotos: GotoDynamic[] = [];
  const lines = cobolCode.split('\n');
  
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    
    // GO TO para-1, para-2, para-3 DEPENDING ON variable
    const gotoDepMatch = line.match(/GO\s*TO\s+([\w-]+(?:\s*,\s*[\w-]+)*)\s+DEPENDING\s+ON\s+([\w-]+)/i);
    
    if (gotoDepMatch) {
      const targets = gotoDepMatch[1].split(',').map(t => t.trim());
      gotos.push({
        line: i + 1,
        targets,
        dependingOn: gotoDepMatch[2]
      });
    }
  }
  
  return gotos;
}

/**
 * Generate Python state machine for ALTER/GOTO patterns
 */
export function generateStateMachine(
  alters: AlterStatement[], 
  gotos: GotoDynamic[],
  paragraphNames: string[]
): string {
  if (alters.length === 0 && gotos.length === 0) {
    return '# No dynamic control flow detected - no state machine needed';
  }

  let code = `"""
State Machine for Dynamic Control Flow
Generated by CodeSwitch v6.1.0
Handles ALTER and GOTO DEPENDING ON patterns
"""

from enum import Enum, auto
from typing import Callable, Dict, Optional

class ParagraphState(Enum):
    """States representing COBOL paragraphs"""
`;

  // Generate enum values for paragraphs
  const relevantParagraphs = new Set<string>();
  for (const alter of alters) {
    relevantParagraphs.add(alter.originalTarget);
    relevantParagraphs.add(alter.newTarget);
  }
  for (const goto of gotos) {
    goto.targets.forEach(t => relevantParagraphs.add(t));
  }
  
  for (const para of relevantParagraphs) {
    const enumName = para.toUpperCase().replace(/-/g, '_');
    code += `    ${enumName} = auto()\n`;
  }

  code += `
class DynamicControlFlow:
    """
    Manages ALTER and GOTO DEPENDING ON behavior.
    
    In COBOL, ALTER modifies GOTO targets at runtime.
    This class simulates that behavior safely in Python.
    """
    
    def __init__(self):
        # Alterable targets: maps paragraph -> current target
        self._altered_targets: Dict[str, str] = {
`;

  // Initialize alterable targets
  for (const alter of alters) {
    code += `            "${alter.originalTarget}": "${alter.originalTarget}",  # Original target\n`;
  }

  code += `        }
        
        # Paragraph implementations
        self._paragraphs: Dict[str, Callable] = {}
        
        # Execution trace for debugging
        self._trace: list = []
    
    def alter(self, paragraph: str, new_target: str) -> None:
        """
        Simulate COBOL ALTER statement.
        ALTER paragraph TO PROCEED TO new_target
        """
        if paragraph not in self._altered_targets:
            raise ValueError(f"Paragraph {paragraph} is not alterable")
        
        old_target = self._altered_targets[paragraph]
        self._altered_targets[paragraph] = new_target
        self._trace.append(f"ALTER {paragraph}: {old_target} -> {new_target}")
    
    def goto(self, paragraph: str) -> str:
        """
        Get the current target for a potentially altered GOTO.
        Returns the paragraph to actually execute.
        """
        target = self._altered_targets.get(paragraph, paragraph)
        self._trace.append(f"GOTO {paragraph} -> {target}")
        return target
    
    def goto_depending_on(self, index: int, *targets: str) -> Optional[str]:
        """
        Simulate GOTO DEPENDING ON.
        index is 1-based (COBOL convention).
        Returns None if index is out of range.
        """
        if index < 1 or index > len(targets):
            self._trace.append(f"GOTO DEPENDING ON {index}: out of range")
            return None
        
        target = targets[index - 1]
        self._trace.append(f"GOTO DEPENDING ON {index} -> {target}")
        return target
    
    def register_paragraph(self, name: str, impl: Callable) -> None:
        """Register a paragraph implementation"""
        self._paragraphs[name] = impl
    
    def execute(self, paragraph: str) -> None:
        """Execute a paragraph by name"""
        target = self.goto(paragraph)
        if target in self._paragraphs:
            self._paragraphs[target]()
        else:
            raise ValueError(f"Paragraph {target} not registered")
    
    def get_trace(self) -> list:
        """Get execution trace for debugging"""
        return self._trace.copy()
    
    def clear_trace(self) -> None:
        """Clear execution trace"""
        self._trace.clear()


# Example usage for detected patterns:
`;

  // Generate example usage
  if (alters.length > 0) {
    code += `
# ALTER statements detected:
`;
    for (const alter of alters) {
      code += `#   Line ${alter.line}: ALTER ${alter.originalTarget} TO PROCEED TO ${alter.newTarget}\n`;
    }
    
    code += `
def example_alter_usage():
    flow = DynamicControlFlow()
    
    # Simulate the ALTER
`;
    for (const alter of alters) {
      code += `    flow.alter("${alter.originalTarget}", "${alter.newTarget}")\n`;
    }
  }

  if (gotos.length > 0) {
    code += `
# GOTO DEPENDING ON statements detected:
`;
    for (const goto of gotos) {
      code += `#   Line ${goto.line}: GO TO ${goto.targets.join(', ')} DEPENDING ON ${goto.dependingOn}\n`;
    }
    
    code += `
def example_goto_depending_usage():
    flow = DynamicControlFlow()
    
    # Simulate GOTO DEPENDING ON
`;
    for (const goto of gotos) {
      const depVar = goto.dependingOn || 'index';
      code += `    # Based on ${depVar} value (1-${goto.targets.length}):\n`;
      code += `    target = flow.goto_depending_on(${depVar.toLowerCase()}_value, ${goto.targets.map(t => `"${t}"`).join(', ')})\n`;
      code += `    if target:\n`;
      code += `        flow.execute(target)\n`;
    }
  }

  return code;
}

/**
 * Analyze ALTER/GOTO patterns and assess risk
 */
export function analyzeAlterPatterns(cobolCode: string): AlterAnalysis {
  const alters = detectAlterStatements(cobolCode);
  const gotos = detectDynamicGotos(cobolCode);
  const warnings: string[] = [];
  
  // Extract paragraph names
  const paragraphMatches = cobolCode.match(/^[\s]{0,7}([A-Z0-9][\w-]*)\s*\.\s*$/gim) || [];
  const paragraphNames = paragraphMatches.map(m => m.trim().replace('.', ''));
  
  // Determine risk level
  let riskLevel: AlterAnalysis['riskLevel'] = 'LOW';
  
  if (alters.length > 0) {
    riskLevel = 'HIGH';
    warnings.push(`${alters.length} ALTER statement(s) detected - dynamic control flow`);
  }
  
  if (gotos.length > 0) {
    riskLevel = alters.length > 0 ? 'CRITICAL' : 'MEDIUM';
    warnings.push(`${gotos.length} GOTO DEPENDING ON statement(s) detected`);
  }
  
  // Check for circular ALTER patterns
  const alterTargets = new Set(alters.map(a => a.newTarget));
  const alterSources = new Set(alters.map(a => a.originalTarget));
  const circular = [...alterTargets].filter(t => alterSources.has(t));
  if (circular.length > 0) {
    riskLevel = 'CRITICAL';
    warnings.push(`Circular ALTER pattern detected: ${circular.join(', ')}`);
  }
  
  // Extract state variables
  const stateVariables = gotos.map(g => g.dependingOn).filter(Boolean) as string[];
  
  // Generate state machine
  const pythonStateMachine = generateStateMachine(alters, gotos, paragraphNames);
  
  return {
    alterStatements: alters,
    dynamicGotos: gotos,
    riskLevel,
    stateVariables,
    pythonStateMachine,
    warnings
  };
}

/**
 * Format ALTER analysis as report
 */
export function formatAlterReport(analysis: AlterAnalysis): string {
  const riskEmoji = {
    LOW: '🟢',
    MEDIUM: '🟡', 
    HIGH: '🟠',
    CRITICAL: '🔴'
  };

  let report = `
╔══════════════════════════════════════════════════════════════════╗
║         ALTER/GOTO DYNAMIC CONTROL FLOW ANALYSIS                 ║
╚══════════════════════════════════════════════════════════════════╝

${riskEmoji[analysis.riskLevel]} RISK LEVEL: ${analysis.riskLevel}

📊 DETECTED PATTERNS
───────────────────────────────────────────────────────────────────
  ALTER statements:        ${analysis.alterStatements.length}
  GOTO DEPENDING ON:       ${analysis.dynamicGotos.length}
  State variables:         ${analysis.stateVariables.length > 0 ? analysis.stateVariables.join(', ') : 'None'}

`;

  if (analysis.alterStatements.length > 0) {
    report += `📝 ALTER STATEMENTS
───────────────────────────────────────────────────────────────────
`;
    for (const alter of analysis.alterStatements) {
      report += `  Line ${alter.line}: ALTER ${alter.originalTarget} TO ${alter.newTarget}\n`;
    }
    report += '\n';
  }

  if (analysis.dynamicGotos.length > 0) {
    report += `🔀 GOTO DEPENDING ON
───────────────────────────────────────────────────────────────────
`;
    for (const goto of analysis.dynamicGotos) {
      report += `  Line ${goto.line}: GO TO ${goto.targets.join(', ')} DEPENDING ON ${goto.dependingOn}\n`;
    }
    report += '\n';
  }

  if (analysis.warnings.length > 0) {
    report += `⚠️  WARNINGS
───────────────────────────────────────────────────────────────────
`;
    for (const warning of analysis.warnings) {
      report += `  • ${warning}\n`;
    }
  }

  report += `
✅ MITIGATION
───────────────────────────────────────────────────────────────────
  A Python state machine has been generated to safely handle
  the dynamic control flow. See pythonStateMachine property.
`;

  return report;
}
