/**
 * EOF Detection via Fixtures - v6.1.0
 * Détection automatique des comportements EOF différents via fixtures spécifiques
 */

export interface EOFBehavior {
  type: 'AT_END' | 'NOT_AT_END' | 'INVALID_KEY' | 'FILE_STATUS';
  cobolPattern: string;
  pythonEquivalent: string;
  testFixture: string;
}

export interface EOFTestResult {
  behavior: EOFBehavior;
  passed: boolean;
  expectedOutput: string;
  actualOutput: string;
  errorMessage?: string;
}

// EOF behavior patterns found in COBOL
export const EOF_BEHAVIORS: EOFBehavior[] = [
  {
    type: 'AT_END',
    cobolPattern: 'READ file-name AT END',
    pythonEquivalent: 'try: record = file.read() except EOFError:',
    testFixture: `
# EOF Fixture: AT END behavior
def test_at_end_eof():
    """Test that AT END is triggered when file reaches EOF"""
    test_data = ["LINE1", "LINE2", "LINE3"]
    eof_reached = False
    records_read = []
    
    for line in test_data:
        records_read.append(line)
    eof_reached = True  # Simulates AT END
    
    assert eof_reached == True
    assert len(records_read) == 3
    return True
`
  },
  {
    type: 'NOT_AT_END',
    cobolPattern: 'READ file-name NOT AT END',
    pythonEquivalent: 'if record := file.read():',
    testFixture: `
# EOF Fixture: NOT AT END behavior  
def test_not_at_end():
    """Test that NOT AT END processes records correctly"""
    test_data = ["LINE1", "LINE2", "LINE3"]
    processed = []
    
    for line in test_data:
        # NOT AT END - record available
        processed.append(f"PROCESSED: {line}")
    
    assert len(processed) == 3
    assert all("PROCESSED:" in p for p in processed)
    return True
`
  },
  {
    type: 'INVALID_KEY',
    cobolPattern: 'READ file-name INVALID KEY',
    pythonEquivalent: 'try: record = indexed_file[key] except KeyError:',
    testFixture: `
# EOF Fixture: INVALID KEY behavior
def test_invalid_key():
    """Test that INVALID KEY is triggered for missing keys"""
    indexed_data = {"001": "RECORD1", "002": "RECORD2"}
    invalid_key_triggered = False
    
    try:
        record = indexed_data["999"]  # Key doesn't exist
    except KeyError:
        invalid_key_triggered = True
    
    assert invalid_key_triggered == True
    return True
`
  },
  {
    type: 'FILE_STATUS',
    cobolPattern: 'FILE STATUS IS ws-status',
    pythonEquivalent: 'file_status = FileStatus()',
    testFixture: `
# EOF Fixture: FILE STATUS behavior
def test_file_status_eof():
    """Test that FILE STATUS returns '10' at EOF"""
    class FileStatus:
        SUCCESS = "00"
        EOF = "10"
        NOT_FOUND = "23"
        
    status = FileStatus.EOF  # Simulates reaching EOF
    
    assert status == "10"
    return True
`
  }
];

/**
 * Detect EOF patterns in COBOL code
 */
export function detectEOFPatterns(cobolCode: string): EOFBehavior[] {
  const detected: EOFBehavior[] = [];
  const upperCode = cobolCode.toUpperCase();
  
  // Check for AT END pattern
  if (/READ\s+[\w-]+\s+AT\s+END/i.test(upperCode)) {
    detected.push(EOF_BEHAVIORS.find(b => b.type === 'AT_END')!);
  }
  
  // Check for NOT AT END pattern
  if (/READ\s+[\w-]+\s+NOT\s+AT\s+END/i.test(upperCode)) {
    detected.push(EOF_BEHAVIORS.find(b => b.type === 'NOT_AT_END')!);
  }
  
  // Check for INVALID KEY pattern
  if (/READ\s+[\w-]+\s+INVALID\s+KEY/i.test(upperCode)) {
    detected.push(EOF_BEHAVIORS.find(b => b.type === 'INVALID_KEY')!);
  }
  
  // Check for FILE STATUS pattern
  if (/FILE\s+STATUS\s+IS/i.test(upperCode)) {
    detected.push(EOF_BEHAVIORS.find(b => b.type === 'FILE_STATUS')!);
  }
  
  return detected;
}

/**
 * Generate test fixtures for detected EOF behaviors
 */
export function generateEOFFixtures(behaviors: EOFBehavior[]): string {
  let fixtures = `"""
Auto-generated EOF Test Fixtures
Generated by CodeSwitch v6.1.0
"""

import pytest
from decimal import Decimal

`;

  for (const behavior of behaviors) {
    fixtures += behavior.testFixture + '\n\n';
  }
  
  fixtures += `
# Run all EOF tests
def run_all_eof_tests():
    results = []
    tests = [
        ${behaviors.map(b => `test_${b.type.toLowerCase().replace(/_/g, '_')}`).join(',\n        ')}
    ]
    
    for test in tests:
        try:
            test()
            results.append((test.__name__, True, None))
        except AssertionError as e:
            results.append((test.__name__, False, str(e)))
    
    return results

if __name__ == "__main__":
    results = run_all_eof_tests()
    for name, passed, error in results:
        status = "PASS" if passed else "FAIL"
        print(f"{status}: {name}")
        if error:
            print(f"  Error: {error}")
`;

  return fixtures;
}

/**
 * Validate EOF handling in Python code matches COBOL behavior
 */
export function validateEOFHandling(
  cobolCode: string, 
  pythonCode: string
): { valid: boolean; issues: string[] } {
  const issues: string[] = [];
  const detectedBehaviors = detectEOFPatterns(cobolCode);
  
  for (const behavior of detectedBehaviors) {
    const pythonPattern = behavior.pythonEquivalent.split(':')[0];
    
    if (!pythonCode.includes('EOF') && 
        !pythonCode.includes('StopIteration') && 
        !pythonCode.includes('except') &&
        behavior.type === 'AT_END') {
      issues.push(`Missing EOF handling for ${behavior.type} pattern`);
    }
    
    if (behavior.type === 'INVALID_KEY' && !pythonCode.includes('KeyError')) {
      issues.push(`Missing KeyError handling for INVALID KEY pattern`);
    }
    
    if (behavior.type === 'FILE_STATUS' && !pythonCode.toLowerCase().includes('status')) {
      issues.push(`Missing file status tracking for FILE STATUS pattern`);
    }
  }
  
  return {
    valid: issues.length === 0,
    issues
  };
}
