/**
 * CodeSwitch v7.0 - Framework Exporter
 * 
 * Export transpiled Python to specific frameworks:
 * 1. Django (with models, views, urls)
 * 2. FastAPI (with routes, schemas, dependencies)
 * 3. Flask (with blueprints, routes)
 * 4. Plain Python (standalone script)
 */

export type FrameworkTarget = 'django' | 'fastapi' | 'flask' | 'plain';

export interface ExportOptions {
  framework: FrameworkTarget;
  projectName: string;
  includeTests: boolean;
  includeDocker: boolean;
  includeCI: boolean;
  databaseType?: 'postgresql' | 'mysql' | 'sqlite' | 'none';
  authEnabled?: boolean;
}

export interface ExportedFile {
  path: string;
  content: string;
  type: 'python' | 'yaml' | 'dockerfile' | 'config' | 'markdown';
}

export interface ExportResult {
  files: ExportedFile[];
  structure: string;
  setupCommands: string[];
  runCommand: string;
}

/**
 * Main export function
 */
export function exportToFramework(
  pythonCode: string,
  className: string,
  options: ExportOptions
): ExportResult {
  switch (options.framework) {
    case 'django':
      return exportToDjango(pythonCode, className, options);
    case 'fastapi':
      return exportToFastAPI(pythonCode, className, options);
    case 'flask':
      return exportToFlask(pythonCode, className, options);
    case 'plain':
    default:
      return exportToPlain(pythonCode, className, options);
  }
}

/**
 * Export to Django
 */
function exportToDjango(
  pythonCode: string,
  className: string,
  options: ExportOptions
): ExportResult {
  const projectName = options.projectName.toLowerCase().replace(/[^a-z0-9]/g, '_');
  const appName = className.toLowerCase();
  
  const files: ExportedFile[] = [];
  
  // manage.py
  files.push({
    path: 'manage.py',
    content: `#!/usr/bin/env python
"""Django's command-line utility for administrative tasks."""
import os
import sys

def main():
    """Run administrative tasks."""
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', '${projectName}.settings')
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed?"
        ) from exc
    execute_from_command_line(sys.argv)

if __name__ == '__main__':
    main()
`,
    type: 'python'
  });

  // settings.py
  files.push({
    path: `${projectName}/settings.py`,
    content: generateDjangoSettings(projectName, appName, options),
    type: 'python'
  });

  // urls.py (project)
  files.push({
    path: `${projectName}/urls.py`,
    content: `from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('${appName}.urls')),
]
`,
    type: 'python'
  });

  // wsgi.py
  files.push({
    path: `${projectName}/wsgi.py`,
    content: `import os
from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', '${projectName}.settings')
application = get_wsgi_application()
`,
    type: 'python'
  });

  // __init__.py (project)
  files.push({
    path: `${projectName}/__init__.py`,
    content: '',
    type: 'python'
  });

  // App files
  files.push({
    path: `${appName}/__init__.py`,
    content: '',
    type: 'python'
  });

  // models.py
  files.push({
    path: `${appName}/models.py`,
    content: generateDjangoModels(pythonCode, className),
    type: 'python'
  });

  // views.py
  files.push({
    path: `${appName}/views.py`,
    content: generateDjangoViews(pythonCode, className),
    type: 'python'
  });

  // urls.py (app)
  files.push({
    path: `${appName}/urls.py`,
    content: `from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('run/', views.run_${appName}, name='run'),
    path('status/', views.status, name='status'),
]
`,
    type: 'python'
  });

  // services.py (business logic)
  files.push({
    path: `${appName}/services.py`,
    content: `"""
Business logic transpiled from COBOL
Generated by CodeSwitch v7.0
"""

${pythonCode}
`,
    type: 'python'
  });

  // requirements.txt
  files.push({
    path: 'requirements.txt',
    content: `Django>=4.2
${options.databaseType === 'postgresql' ? 'psycopg2-binary>=2.9' : ''}
${options.databaseType === 'mysql' ? 'mysqlclient>=2.1' : ''}
python-dotenv>=1.0
`,
    type: 'config'
  });

  // Tests
  if (options.includeTests) {
    files.push({
      path: `${appName}/tests.py`,
      content: generateDjangoTests(className, appName),
      type: 'python'
    });
  }

  // Docker
  if (options.includeDocker) {
    files.push(...generateDockerFiles(options.framework, projectName));
  }

  // CI
  if (options.includeCI) {
    files.push(generateGitHubActions(options.framework, projectName));
  }

  return {
    files,
    structure: generateStructureTree(files),
    setupCommands: [
      'python -m venv venv',
      'source venv/bin/activate  # or venv\\Scripts\\activate on Windows',
      'pip install -r requirements.txt',
      'python manage.py migrate',
      'python manage.py createsuperuser'
    ],
    runCommand: 'python manage.py runserver'
  };
}

/**
 * Export to FastAPI
 */
function exportToFastAPI(
  pythonCode: string,
  className: string,
  options: ExportOptions
): ExportResult {
  const projectName = options.projectName.toLowerCase().replace(/[^a-z0-9]/g, '_');
  
  const files: ExportedFile[] = [];

  // main.py
  files.push({
    path: 'app/main.py',
    content: `"""
FastAPI Application - ${options.projectName}
Generated by CodeSwitch v7.0
"""

from fastapi import FastAPI, HTTPException, Depends
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional, Dict, Any
from .services import ${className}

app = FastAPI(
    title="${options.projectName}",
    description="Transpiled from COBOL by CodeSwitch",
    version="1.0.0"
)

# CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Schemas
class RunRequest(BaseModel):
    params: Optional[Dict[str, Any]] = None

class RunResponse(BaseModel):
    success: bool
    result: Optional[Dict[str, Any]] = None
    error: Optional[str] = None

class StatusResponse(BaseModel):
    status: str
    version: str

# Instance
_instance: Optional[${className}] = None

def get_instance() -> ${className}:
    global _instance
    if _instance is None:
        _instance = ${className}()
    return _instance

# Routes
@app.get("/")
async def root():
    return {"message": "Welcome to ${options.projectName} API"}

@app.get("/status", response_model=StatusResponse)
async def status():
    return StatusResponse(status="healthy", version="1.0.0")

@app.post("/run", response_model=RunResponse)
async def run(
    request: RunRequest,
    instance: ${className} = Depends(get_instance)
):
    try:
        if hasattr(instance, 'run'):
            result = instance.run()
        else:
            result = None
        
        # Get instance attributes as result
        output = {
            k: str(v) for k, v in vars(instance).items() 
            if not k.startswith('_')
        }
        
        return RunResponse(success=True, result=output)
    except Exception as e:
        return RunResponse(success=False, error=str(e))

@app.get("/attributes")
async def get_attributes(instance: ${className} = Depends(get_instance)):
    return {
        k: str(v) for k, v in vars(instance).items() 
        if not k.startswith('_')
    }
`,
    type: 'python'
  });

  // services.py
  files.push({
    path: 'app/services.py',
    content: `"""
Business logic transpiled from COBOL
Generated by CodeSwitch v7.0
"""

${pythonCode}
`,
    type: 'python'
  });

  // __init__.py
  files.push({
    path: 'app/__init__.py',
    content: '',
    type: 'python'
  });

  // requirements.txt
  files.push({
    path: 'requirements.txt',
    content: `fastapi>=0.100.0
uvicorn[standard]>=0.22.0
pydantic>=2.0
python-dotenv>=1.0
${options.databaseType === 'postgresql' ? 'asyncpg>=0.27\nsqlalchemy>=2.0' : ''}
${options.databaseType === 'mysql' ? 'aiomysql>=0.1\nsqlalchemy>=2.0' : ''}
`,
    type: 'config'
  });

  // Tests
  if (options.includeTests) {
    files.push({
      path: 'tests/test_main.py',
      content: generateFastAPITests(className),
      type: 'python'
    });
    files.push({
      path: 'tests/__init__.py',
      content: '',
      type: 'python'
    });
  }

  // Docker
  if (options.includeDocker) {
    files.push(...generateDockerFiles(options.framework, projectName));
  }

  // CI
  if (options.includeCI) {
    files.push(generateGitHubActions(options.framework, projectName));
  }

  return {
    files,
    structure: generateStructureTree(files),
    setupCommands: [
      'python -m venv venv',
      'source venv/bin/activate',
      'pip install -r requirements.txt'
    ],
    runCommand: 'uvicorn app.main:app --reload'
  };
}

/**
 * Export to Flask
 */
function exportToFlask(
  pythonCode: string,
  className: string,
  options: ExportOptions
): ExportResult {
  const projectName = options.projectName.toLowerCase().replace(/[^a-z0-9]/g, '_');
  
  const files: ExportedFile[] = [];

  // app.py
  files.push({
    path: 'app/__init__.py',
    content: `"""
Flask Application - ${options.projectName}
Generated by CodeSwitch v7.0
"""

from flask import Flask
from flask_cors import CORS

def create_app():
    app = Flask(__name__)
    CORS(app)
    
    app.config['SECRET_KEY'] = 'your-secret-key-change-in-production'
    
    from .routes import main_bp
    app.register_blueprint(main_bp)
    
    return app
`,
    type: 'python'
  });

  // routes.py
  files.push({
    path: 'app/routes.py',
    content: `"""
Flask Routes
Generated by CodeSwitch v7.0
"""

from flask import Blueprint, jsonify, request
from .services import ${className}

main_bp = Blueprint('main', __name__)

# Instance
_instance = None

def get_instance():
    global _instance
    if _instance is None:
        _instance = ${className}()
    return _instance

@main_bp.route('/')
def index():
    return jsonify({"message": "Welcome to ${options.projectName} API"})

@main_bp.route('/status')
def status():
    return jsonify({"status": "healthy", "version": "1.0.0"})

@main_bp.route('/run', methods=['POST'])
def run():
    try:
        instance = get_instance()
        if hasattr(instance, 'run'):
            instance.run()
        
        output = {
            k: str(v) for k, v in vars(instance).items() 
            if not k.startswith('_')
        }
        
        return jsonify({"success": True, "result": output})
    except Exception as e:
        return jsonify({"success": False, "error": str(e)}), 500

@main_bp.route('/attributes')
def get_attributes():
    instance = get_instance()
    return jsonify({
        k: str(v) for k, v in vars(instance).items() 
        if not k.startswith('_')
    })
`,
    type: 'python'
  });

  // services.py
  files.push({
    path: 'app/services.py',
    content: `"""
Business logic transpiled from COBOL
Generated by CodeSwitch v7.0
"""

${pythonCode}
`,
    type: 'python'
  });

  // run.py
  files.push({
    path: 'run.py',
    content: `from app import create_app

app = create_app()

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=5000)
`,
    type: 'python'
  });

  // requirements.txt
  files.push({
    path: 'requirements.txt',
    content: `Flask>=2.3.0
flask-cors>=4.0.0
python-dotenv>=1.0
gunicorn>=21.0
${options.databaseType === 'postgresql' ? 'psycopg2-binary>=2.9\nflask-sqlalchemy>=3.0' : ''}
${options.databaseType === 'mysql' ? 'pymysql>=1.0\nflask-sqlalchemy>=3.0' : ''}
`,
    type: 'config'
  });

  // Tests
  if (options.includeTests) {
    files.push({
      path: 'tests/test_app.py',
      content: generateFlaskTests(className),
      type: 'python'
    });
    files.push({
      path: 'tests/__init__.py',
      content: '',
      type: 'python'
    });
  }

  // Docker
  if (options.includeDocker) {
    files.push(...generateDockerFiles(options.framework, projectName));
  }

  // CI
  if (options.includeCI) {
    files.push(generateGitHubActions(options.framework, projectName));
  }

  return {
    files,
    structure: generateStructureTree(files),
    setupCommands: [
      'python -m venv venv',
      'source venv/bin/activate',
      'pip install -r requirements.txt'
    ],
    runCommand: 'python run.py'
  };
}

/**
 * Export to Plain Python
 */
function exportToPlain(
  pythonCode: string,
  className: string,
  options: ExportOptions
): ExportResult {
  const files: ExportedFile[] = [];

  // main.py
  files.push({
    path: 'main.py',
    content: `#!/usr/bin/env python3
"""
${options.projectName}
Transpiled from COBOL by CodeSwitch v7.0
"""

${pythonCode}

if __name__ == "__main__":
    system = ${className}()
    if hasattr(system, 'run'):
        system.run()
    
    # Display results
    print("\\n=== Results ===")
    for key, value in vars(system).items():
        if not key.startswith('_'):
            print(f"{key}: {value}")
`,
    type: 'python'
  });

  // requirements.txt
  files.push({
    path: 'requirements.txt',
    content: `# Core dependencies
python-dotenv>=1.0
`,
    type: 'config'
  });

  // Tests
  if (options.includeTests) {
    files.push({
      path: 'tests/test_main.py',
      content: `"""
Tests for ${className}
Generated by CodeSwitch v7.0
"""

import pytest
from main import ${className}

class Test${className}:
    def test_initialization(self):
        system = ${className}()
        assert system is not None
    
    def test_run(self):
        system = ${className}()
        if hasattr(system, 'run'):
            system.run()
        assert True
`,
      type: 'python'
    });
  }

  return {
    files,
    structure: generateStructureTree(files),
    setupCommands: [
      'python -m venv venv',
      'source venv/bin/activate',
      'pip install -r requirements.txt'
    ],
    runCommand: 'python main.py'
  };
}

// Helper functions
function generateDjangoSettings(projectName: string, appName: string, options: ExportOptions): string {
  const dbConfig = options.databaseType === 'postgresql' 
    ? `'ENGINE': 'django.db.backends.postgresql',
        'NAME': '${projectName}',
        'USER': 'postgres',
        'PASSWORD': 'password',
        'HOST': 'localhost',
        'PORT': '5432',`
    : options.databaseType === 'mysql'
    ? `'ENGINE': 'django.db.backends.mysql',
        'NAME': '${projectName}',
        'USER': 'root',
        'PASSWORD': 'password',
        'HOST': 'localhost',
        'PORT': '3306',`
    : `'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',`;

  return `from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-change-this-in-production'
DEBUG = True
ALLOWED_HOSTS = ['*']

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    '${appName}',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
]

ROOT_URLCONF = '${projectName}.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

DATABASES = {
    'default': {
        ${dbConfig}
    }
}

STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
`;
}

function generateDjangoModels(pythonCode: string, className: string): string {
  return `from django.db import models

class ${className}Run(models.Model):
    """Track execution runs"""
    created_at = models.DateTimeField(auto_now_add=True)
    completed_at = models.DateTimeField(null=True, blank=True)
    status = models.CharField(max_length=20, default='pending')
    result = models.JSONField(null=True, blank=True)
    
    class Meta:
        ordering = ['-created_at']
`;
}

function generateDjangoViews(pythonCode: string, className: string): string {
  const appName = className.toLowerCase();
  return `from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods
from .services import ${className}
import json

def index(request):
    return JsonResponse({"message": "Welcome to ${className} API"})

@csrf_exempt
@require_http_methods(["POST"])
def run_${appName}(request):
    try:
        system = ${className}()
        if hasattr(system, 'run'):
            system.run()
        
        result = {
            k: str(v) for k, v in vars(system).items() 
            if not k.startswith('_')
        }
        
        return JsonResponse({"success": True, "result": result})
    except Exception as e:
        return JsonResponse({"success": False, "error": str(e)}, status=500)

def status(request):
    return JsonResponse({"status": "healthy", "version": "1.0.0"})
`;
}

function generateDjangoTests(className: string, appName: string): string {
  return `from django.test import TestCase, Client
from .services import ${className}

class ${className}Tests(TestCase):
    def setUp(self):
        self.client = Client()
        self.system = ${className}()
    
    def test_index(self):
        response = self.client.get('/api/')
        self.assertEqual(response.status_code, 200)
    
    def test_status(self):
        response = self.client.get('/api/status/')
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.json()['status'], 'healthy')
    
    def test_run(self):
        response = self.client.post('/api/run/')
        self.assertEqual(response.status_code, 200)
        self.assertTrue(response.json()['success'])
    
    def test_service_initialization(self):
        self.assertIsNotNone(self.system)
`;
}

function generateFastAPITests(className: string): string {
  return `from fastapi.testclient import TestClient
from app.main import app
from app.services import ${className}
import pytest

client = TestClient(app)

class Test${className}API:
    def test_root(self):
        response = client.get("/")
        assert response.status_code == 200
    
    def test_status(self):
        response = client.get("/status")
        assert response.status_code == 200
        assert response.json()["status"] == "healthy"
    
    def test_run(self):
        response = client.post("/run", json={"params": {}})
        assert response.status_code == 200
        assert response.json()["success"] == True
    
    def test_attributes(self):
        response = client.get("/attributes")
        assert response.status_code == 200

class Test${className}Service:
    def test_initialization(self):
        system = ${className}()
        assert system is not None
`;
}

function generateFlaskTests(className: string): string {
  return `import pytest
from app import create_app
from app.services import ${className}

@pytest.fixture
def client():
    app = create_app()
    app.config['TESTING'] = True
    with app.test_client() as client:
        yield client

class Test${className}API:
    def test_index(self, client):
        response = client.get('/')
        assert response.status_code == 200
    
    def test_status(self, client):
        response = client.get('/status')
        assert response.status_code == 200
        assert response.json['status'] == 'healthy'
    
    def test_run(self, client):
        response = client.post('/run')
        assert response.status_code == 200
        assert response.json['success'] == True

class Test${className}Service:
    def test_initialization(self):
        system = ${className}()
        assert system is not None
`;
}

function generateDockerFiles(framework: FrameworkTarget, projectName: string): ExportedFile[] {
  const port = framework === 'django' ? '8000' : framework === 'fastapi' ? '8000' : '5000';
  const cmd = framework === 'django' 
    ? 'gunicorn ${projectName}.wsgi:application --bind 0.0.0.0:8000'
    : framework === 'fastapi'
    ? 'uvicorn app.main:app --host 0.0.0.0 --port 8000'
    : 'gunicorn -b 0.0.0.0:5000 "app:create_app()"';

  return [
    {
      path: 'Dockerfile',
      content: `FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE ${port}

CMD ["${cmd.split(' ')[0]}", ${cmd.split(' ').slice(1).map(s => `"${s}"`).join(', ')}]
`,
      type: 'dockerfile'
    },
    {
      path: 'docker-compose.yml',
      content: `version: '3.8'

services:
  app:
    build: .
    ports:
      - "${port}:${port}"
    environment:
      - DEBUG=false
    volumes:
      - .:/app
`,
      type: 'yaml'
    }
  ];
}

function generateGitHubActions(framework: FrameworkTarget, projectName: string): ExportedFile {
  return {
    path: '.github/workflows/ci.yml',
    content: `name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    
    - name: Run tests
      run: pytest --cov=./ --cov-report=xml
`,
    type: 'yaml'
  };
}

function generateStructureTree(files: ExportedFile[]): string {
  const tree: { [key: string]: any } = {};
  
  files.forEach(file => {
    const parts = file.path.split('/');
    let current = tree;
    parts.forEach((part, i) => {
      if (i === parts.length - 1) {
        current[part] = null;
      } else {
        if (!current[part]) current[part] = {};
        current = current[part];
      }
    });
  });
  
  function renderTree(obj: any, prefix = ''): string {
    let result = '';
    const keys = Object.keys(obj).sort();
    keys.forEach((key, i) => {
      const isLast = i === keys.length - 1;
      const connector = isLast ? '└── ' : '├── ';
      const extension = isLast ? '    ' : '│   ';
      
      result += prefix + connector + key + '\n';
      if (obj[key] !== null) {
        result += renderTree(obj[key], prefix + extension);
      }
    });
    return result;
  }
  
  return renderTree(tree);
}
