"""
MEGA-ENTERPRISE-SYSTEM - Migrated from COBOL
Original: 10006 lines COBOL | Variables: 764 | Paragraphs: 1704
Generated by CodeSwitch AI
"""
from dataclasses import dataclass, field
from decimal import Decimal
from typing import Optional, List, Dict, Any
from datetime import date, datetime
import logging

logger = logging.getLogger('MEGA-ENTERPRISE-SYSTEM')

logger = logging.getLogger(__name__)

@dataclass
class CustomerRecordC1:
    """
    Represents a customer record in the customer_master file
    This data
class maps directly to the COBOL structure defined for
    the customer_master file, ensuring data integrity during migration
    Attributes:
        cust_id (str): Customer identifier (PIC X(12))
        cust_type (str): Customer type (PIC X(1)), 'I', 'C', or 'G'
        cust_last_name (str): Customer's last name (PIC X(30))'
        cust_first_name (str): Customer's first name (PIC X(20))'
        cust_middle_name (str): Customer's middle name (PIC X(15))'
        cust_street (str): Customer's street address (PIC X(50))'
        cust_city (str): Customer's city (PIC X(30))'
        cust_state (str): Customer's state (PIC X(2))'
        cust_zip (str): Customer's zip code (PIC X(10))'
        cust_country (str): Customer's country (PIC X(3))'
        cust_phone (str): Customer's phone number (PIC X(15))'
        cust_email (str): Customer's email address (PIC X(50))'
        cust_fax (str): Customer's fax number (PIC X(15))'
        cust_dob (str): Customer's date of birth (PIC 9(8))'
        cust_ssn (str): Customer's social security number (PIC X(11))'
        cust_tax_id (str): Customer's tax identification number (PIC X(15))'
        cust_credit_score (int): Customer's credit score (PIC 9(3))'
        cust_risk_rating (str): Customer's risk rating (PIC X(1))'
        cust_status (str): Customer's status (PIC X(1)), 'A', 'I', 'S', or 'C''
        cust_open_date (str): Customer's account open date (PIC 9(8))'
        cust_last_activity (str): Customer's last activity date (PIC 9(8))'
        cust_total_balance (Decimal): Customer's total balance (PIC S9(15)V99 comp_3)'
        cust_total_loans (Decimal): Customer's total loans (PIC S9(15)V99 comp_3)'
        cust_total_investments (Decimal): Customer's total investments (PIC S9(15)V99 comp_3)'
    """
    cust_id: str
    cust_type: str
    cust_last_name: str
    cust_first_name: str
    cust_middle_name: str
    cust_street: str
    cust_city: str
    cust_state: str
    cust_zip: str
    cust_country: str
    cust_phone: str
    cust_email: str
    cust_fax: str
    cust_dob: str
    cust_ssn: str
    cust_tax_id: str
    cust_credit_score: int
    cust_risk_rating: str
    cust_status: str
    cust_open_date: str
    cust_last_activity: str
    cust_total_balance: Decimal
    cust_total_loans: Decimal
    cust_total_investments: Decimal

    
def __post_init__(self):
    """TODO"""
    """
        Validates the fields of the CustomerRecord dataclass
        Raises:
            ValueError: If any field fails validation
        """
    logger.info("Validating CustomerRecordC1 instance.")
    try:
        if not isinstance(self.cust_id, str) or len(self.cust_id) > 12:
            logger.error(f"Invalid cust_id: {self.cust_id}")
            raise ValueError("cust_id must be a string of length <= 12")
        if not isinstance(self.cust_type, str) or len(self.cust_type) != 1 or self.cust_type not in ('I', 'C', 'G'):
            logger.error(f"Invalid cust_type: {self.cust_type}")
            raise ValueError("cust_type must be a string of length 1 and 'I', 'C', or 'G'")
        if not isinstance(self.cust_last_name, str) or len(self.cust_last_name) > 30:
            logger.error(f"Invalid cust_last_name: {self.cust_last_name}")
            raise ValueError("cust_last_name must be a string of length <= 30")
        if not isinstance(self.cust_first_name, str) or len(self.cust_first_name) > 20:
            logger.error(f"Invalid cust_first_name: {self.cust_first_name}")
            raise ValueError("cust_first_name must be a string of length <= 20")
        if not isinstance(self.cust_middle_name, str) or len(self.cust_middle_name) > 15:
            logger.error(f"Invalid cust_middle_name: {self.cust_middle_name}")
            raise ValueError("cust_middle_name must be a string of length <= 15")
        if not isinstance(self.cust_street, str) or len(self.cust_street) > 50:
            logger.error(f"Invalid cust_street: {self.cust_street}")
            raise ValueError("cust_street must be a string of length <= 50")
        if not isinstance(self.cust_city, str) or len(self.cust_city) > 30:
            logger.error(f"Invalid cust_city: {self.cust_city}")
            raise ValueError("cust_city must be a string of length <= 30")
        if not isinstance(self.cust_state, str) or len(self.cust_state) > 2:
            logger.error(f"Invalid cust_state: {self.cust_state}")
            raise ValueError("cust_state must be a string of length <= 2")
        if not isinstance(self.cust_zip, str) or len(self.cust_zip) > 10:
            logger.error(f"Invalid cust_zip: {self.cust_zip}")
            raise ValueError("cust_zip must be a string of length <= 10")
        if not isinstance(self.cust_country, str) or len(self.cust_country) > 3:
            logger.error(f"Invalid cust_country: {self.cust_country}")
            raise ValueError("cust_country must be a string of length <= 3")
        if not isinstance(self.cust_phone, str) or len(self.cust_phone) > 15:
            logger.error(f"Invalid cust_phone: {self.cust_phone}")
            raise ValueError("cust_phone must be a string of length <= 15")
        if not isinstance(self.cust_email, str) or len(self.cust_email) > 50:
            logger.error(f"Invalid cust_email: {self.cust_email}")
            raise ValueError("cust_email must be a string of length <= 50")
        if not isinstance(self.cust_fax, str) or len(self.cust_fax) > 15:
            logger.error(f"Invalid cust_fax: {self.cust_fax}")
            raise ValueError("cust_fax must be a string of length <= 15")
        if not isinstance(self.cust_dob, str) or len(self.cust_dob) != 8:
            logger.error(f"Invalid cust_dob: {self.cust_dob}")
            raise ValueError("cust_dob must be a string of length 8")
        if not isinstance(self.cust_ssn, str) or len(self.cust_ssn) > 11:
            logger.error(f"Invalid cust_ssn: {self.cust_ssn}")
            raise ValueError("cust_ssn must be a string of length <= 11")
        if not isinstance(self.cust_tax_id, str) or len(self.cust_tax_id) > 15:
            logger.error(f"Invalid cust_tax_id: {self.cust_tax_id}")
            raise ValueError("cust_tax_id must be a string of length <= 15")
        if not isinstance(self.cust_credit_score, int) or not (0 <= self.cust_credit_score <= 999):
            logger.error(f"Invalid cust_credit_score: {self.cust_credit_score}")
            raise ValueError("cust_credit_score must be an int between 0 and 999")
        if not isinstance(self.cust_risk_rating, str) or len(self.cust_risk_rating) != 1:
            logger.error(f"Invalid cust_risk_rating: {self.cust_risk_rating}")
            raise ValueError("cust_risk_rating must be a string of length 1")
        if not isinstance(self.cust_status, str) or len(self.cust_status) != 1 or self.cust_status not in ('A', 'I', 'S', 'C'):
            logger.error(f"Invalid cust_status: {self.cust_status}")
            raise ValueError("cust_status must be a string of length 1 and 'A', 'I', 'S', or 'C'")
        if not isinstance(self.cust_open_date, str) or len(self.cust_open_date) != 8:
            logger.error(f"Invalid cust_open_date: {self.cust_open_date}")
            raise ValueError("cust_open_date must be a string of length 8")
        if not isinstance(self.cust_last_activity, str) or len(self.cust_last_activity) != 8:
            logger.error(f"Invalid cust_last_activity: {self.cust_last_activity}")
            raise ValueError("cust_last_activity must be a string of length 8")
        if not isinstance(self.cust_total_balance, Decimal):
            logger.error(f"Invalid cust_total_balance: {self.cust_total_balance}")
            raise ValueError("cust_total_balance must be a Decimal")
        if not isinstance(self.cust_total_loans, Decimal):
            logger.error(f"Invalid cust_total_loans: {self.cust_total_loans}")
            raise ValueError("cust_total_loans must be a Decimal")
        if not isinstance(self.cust_total_investments, Decimal):
            logger.error(f"Invalid cust_total_investments: {self.cust_total_investments}")
            raise ValueError("cust_total_investments must be a Decimal")

    except ValueError as e:
        logger.error(f"Validation error: {e}")
        raise

@dataclass
class AccountRecordC1:
    """
    Represents an account record in the account_master file
    Attributes:
        acct_id (str): Account identifier (PIC X(16))
        acct_cust_id (str): Customer identifier associated with the account (PIC X(12))
        acct_type (str): Account type (PIC X(2)), e.g., 'CH', 'SV', 'MM', 'CD', 'IR'
        acct_balance (Decimal): Account balance (PIC S9(13)V99 comp_3)
        acct_available (Decimal): Available balance (PIC S9(13)V99 comp_3)
        acct_pending (Decimal): Pending transactions (PIC S9(13)V99 comp_3)
        acct_interest_rate (Decimal): Interest rate (PIC V9(6) comp_3)
        acct_open_date (str): Account opening date (PIC 9(8))
        acct_last_trans_date (str): Date of the last transaction (PIC 9(8))
        acct_status (str): Account status (PIC X(1))
        acct_overdraft_limit (Decimal): Overdraft limit (PIC S9(9)V99 comp_3)
        acct_monthly_fee (Decimal): Monthly fee (PIC S9(5)V99 comp_3)
        acct_min_balance (Decimal): Minimum balance required (PIC S9(9)V99 comp_3)
    """
    acct_id: str
    acct_cust_id: str
    acct_type: str
    acct_balance: Decimal
    acct_available: Decimal
    acct_pending: Decimal
    acct_interest_rate: Decimal
    acct_open_date: str
    acct_last_trans_date: str
    acct_status: str
    acct_overdraft_limit: Decimal
    acct_monthly_fee: Decimal
    acct_min_balance: Decimal

    
    
def __post_init__(self):
        """TODO"""
        """
        Validates the fields of the AccountRecord dataclass
        Raises:
            ValueError: If any field fails validation
        """
        logger.info("Validating AccountRecordC1 instance.")
        try:
            if not isinstance(self.acct_id, str) or len(self.acct_id) > 16:
                logger.error(f"Invalid acct_id: {self.acct_id}")
                raise ValueError("acct_id must be a string of length <= 16")
            if not isinstance(self.acct_cust_id, str) or len(self.acct_cust_id) > 12:
                logger.error(f"Invalid acct_cust_id: {self.acct_cust_id}")
                raise ValueError("acct_cust_id must be a string of length <= 12")
            if not isinstance(self.acct_type, str) or len(self.acct_type) > 2:
                logger.error(f"Invalid acct_type: {self.acct_type}")
                raise ValueError("acct_type must be a string of length <= 2")
            if not isinstance(self.acct_balance, Decimal):
                logger.error(f"Invalid acct_balance: {self.acct_balance}")
                raise ValueError("acct_balance must be a Decimal")
            if not isinstance(self.acct_available, Decimal):
                logger.error(f"Invalid acct_available: {self.acct_available}")
                raise ValueError("acct_available must be a Decimal")
            if not isinstance(self.acct_pending, Decimal):
                logger.error(f"Invalid acct_pending: {self.acct_pending}")
                raise ValueError("acct_pending must be a Decimal")
            if not isinstance(self.acct_interest_rate, Decimal):
                logger.error(f"Invalid acct_interest_rate: {self.acct_interest_rate}")
                raise ValueError("acct_interest_rate must be a Decimal")
            if not isinstance(self.acct_open_date, str) or len(self.acct_open_date) != 8:
                logger.error(f"Invalid acct_open_date: {self.acct_open_date}")
                raise ValueError("acct_open_date must be a string of length 8")
            if not isinstance(self.acct_last_trans_date, str) or len(self.acct_last_trans_date) != 8:
                logger.error(f"Invalid acct_last_trans_date: {self.acct_last_trans_date}")
                raise ValueError("acct_last_trans_date must be a string of length 8")
            if not isinstance(self.acct_status, str) or len(self.acct_status) != 1:
                logger.error(f"Invalid acct_status: {self.acct_status}")
                raise ValueError("acct_status must be a string of length 1")
            if not isinstance(self.acct_overdraft_limit, Decimal):
                logger.error(f"Invalid acct_overdraft_limit: {self.acct_overdraft_limit}")
                raise ValueError("acct_overdraft_limit must be a Decimal")
            if not isinstance(self.acct_monthly_fee, Decimal):
                logger.error(f"Invalid acct_monthly_fee: {self.acct_monthly_fee}")
                raise ValueError("acct_monthly_fee must be a Decimal")
            if not isinstance(self.acct_min_balance, Decimal):
                logger.error(f"Invalid acct_min_balance: {self.acct_min_balance}")
                raise ValueError("acct_min_balance must be a Decimal")

        except ValueError as e:
            logger.error(f"Validation error: {e}")
            raise

@dataclass
class LoanRecordC1:
    """
    Represents a loan record in the loan_master file
    Attributes:
        loan_id (str): Loan identifier (PIC X(16))
        loan_cust_id (str): Customer identifier associated with the loan (PIC X(12))
        loan_type (str): Loan type (PIC X(2)), e.g., 'MG', 'AU', 'PE', 'BU', 'ST', 'HE'
        loan_original_amount (Decimal): Original loan amount (PIC S9(13)V99 comp_3)
        loan_current_balance (Decimal): Current loan balance (PIC S9(13)V99 comp_3)
        loan_interest_rate (Decimal): Interest rate (PIC V9(6) comp_3)
        loan_term_months (int): Loan term in months (PIC 9(4))
        loan_payment_amount (Decimal): Payment amount (PIC S9(9)V99 comp_3)
        loan_next_payment_date (str): Next payment date (PIC 9(8))
        loan_origination_date (str): Loan origination date (PIC 9(8))
        loan_maturity_date (str): Loan maturity date (PIC 9(8))
        loan_status (str): Loan status (PIC X(1))
        loan_collateral_value (Decimal): Collateral value (PIC S9(13)V99 comp_3)
        loan_ltv_ratio (Decimal): Loan-to-value ratio (PIC V999)
    """
    loan_id: str
    loan_cust_id: str
    loan_type: str
    loan_original_amount: Decimal
    loan_current_balance: Decimal
    loan_interest_rate: Decimal
    loan_term_months: int
    loan_payment_amount: Decimal
    loan_next_payment_date: str
    loan_origination_date: str
    loan_maturity_date: str
    loan_status: str
    loan_collateral_value: Decimal
    loan_ltv_ratio: Decimal

    
def __post_init__(self):
    """TODO"""
    """
        Validates the fields of the LoanRecord dataclass
        Raises:
            ValueError: If any field fails validation
        """
    logger.info("Validating LoanRecordC1 instance.")
    try:
        if not isinstance(self.loan_id, str) or len(self.loan_id) > 16:
            logger.error(f"Invalid loan_id: {self.loan_id}")
            raise ValueError("loan_id must be a string of length <= 16")
        if not isinstance(self.loan_cust_id, str) or len(self.loan_cust_id) > 12:
            logger.error(f"Invalid loan_cust_id: {self.loan_cust_id}")
            raise ValueError("loan_cust_id must be a string of length <= 12")
        if not isinstance(self.loan_type, str) or len(self.loan_type) > 2:
            logger.error(f"Invalid loan_type: {self.loan_type}")
            raise ValueError("loan_type must be a string of length <= 2")
        if not isinstance(self.loan_original_amount, Decimal):
            logger.error(f"Invalid loan_original_amount: {self.loan_original_amount}")
            raise ValueError("loan_original_amount must be a Decimal")
        if not isinstance(self.loan_current_balance, Decimal):
            logger.error(f"Invalid loan_current_balance: {self.loan_current_balance}")
            raise ValueError("loan_current_balance must be a Decimal")
        if not isinstance(self.loan_interest_rate, Decimal):
            logger.error(f"Invalid loan_interest_rate: {self.loan_interest_rate}")
            raise ValueError("loan_interest_rate must be a Decimal")
        if not isinstance(self.loan_term_months, int) or not (0 <= self.loan_term_months <= 9999):
            logger.error(f"Invalid loan_term_months: {self.loan_term_months}")
            raise ValueError("loan_term_months must be an int between 0 and 9999")
        if not isinstance(self.loan_payment_amount, Decimal):
            logger.error(f"Invalid loan_payment_amount: {self.loan_payment_amount}")
            raise ValueError("loan_payment_amount must be a Decimal")
        if not isinstance(self.loan_next_payment_date, str) or len(self.loan_next_payment_date) != 8:
            logger.error(f"Invalid loan_next_payment_date: {self.loan_next_payment_date}")
            raise ValueError("loan_next_payment_date must be a string of length 8")
        if not isinstance(self.loan_origination_date, str) or len(self.loan_origination_date) != 8:
            logger.error(f"Invalid loan_origination_date: {self.loan_origination_date}")
            raise ValueError("loan_origination_date must be a string of length 8")
        if not isinstance(self.loan_maturity_date, str) or len(self.loan_maturity_date) != 8:
            logger.error(f"Invalid loan_maturity_date: {self.loan_maturity_date}")
            raise ValueError("loan_maturity_date must be a string of length 8")
        if not isinstance(self.loan_status, str) or len(self.loan_status) != 1:
            logger.error(f"Invalid loan_status: {self.loan_status}")
            raise ValueError("loan_status must be a string of length 1")
        if not isinstance(self.loan_collateral_value, Decimal):
            logger.error(f"Invalid loan_collateral_value: {self.loan_collateral_value}")
            raise ValueError("loan_collateral_value must be a Decimal")
        if not isinstance(self.loan_ltv_ratio, Decimal):
            logger.error(f"Invalid loan_ltv_ratio: {self.loan_ltv_ratio}")
            raise ValueError("loan_ltv_ratio must be a Decimal")

    except ValueError as e:
        logger.error(f"Validation error: {e}")
        raise
            
@dataclass
class InsuranceRecordC1:
    """
    Represents an insurance record in the insurance_master file
    Attributes:
        ins_policy_id (str): Insurance policy identifier (PIC X(16))
        ins_cust_id (str): Customer identifier associated with the insurance policy (PIC X(12))
        ins_type (str): Insurance type (PIC X(2)), e.g., 'LI', 'HE', 'AU', 'HO', 'UM'
        ins_coverage_amount (Decimal): Coverage amount (PIC S9(13)V99 comp_3)
        ins_premium_amount (Decimal): Premium amount (PIC S9(9)V99 comp_3)
        ins_deductible (Decimal): Deductible amount (PIC S9(9)V99 comp_3)
        ins_effective_date (str): Effective date (PIC 9(8))
        ins_expiry_date (str): Expiry date (PIC 9(8))
        ins_status (str): Insurance status (PIC X(1))
        ins_claims_count (int): Number of claims (PIC 9(4))
        ins_total_claims (Decimal): Total claims amount (PIC S9(13)V99 comp_3)
    """
    ins_policy_id: str
    ins_cust_id: str
    ins_type: str
    ins_coverage_amount: Decimal
    ins_premium_amount: Decimal
    ins_deductible: Decimal
    ins_effective_date: str
    ins_expiry_date: str
    ins_status: str
    ins_claims_count: int
    ins_total_claims: Decimal

    
def __post_init__(self):
    """TODO"""
    """
        Validates the fields of the InsuranceRecord dataclass
        Raises:
            ValueError: If any field fails validation
        """
    logger.info("Validating InsuranceRecordC1 instance.")
    try:
        if not isinstance(self.ins_policy_id, str) or len(self.ins_policy_id) > 16:
            logger.error(f"Invalid ins_policy_id: {self.ins_policy_id}")
            raise ValueError("ins_policy_id must be a string of length <= 16")
        if not isinstance(self.ins_cust_id, str) or len(self.ins_cust_id) > 12:
            logger.error(f"Invalid ins_cust_id: {self.ins_cust_id}")
            raise ValueError("ins_cust_id must be a string of length <= 12")
        if not isinstance(self.ins_type, str) or len(self.ins_type) > 2:
            logger.error(f"Invalid ins_type: {self.ins_type}")
            raise ValueError("ins_type must be a string of length <= 2")
        if not isinstance(self.ins_coverage_amount, Decimal):
            logger.error(f"Invalid ins_coverage_amount: {self.ins_coverage_amount}")
            raise ValueError("ins_coverage_amount must be a Decimal")
        if not isinstance(self.ins_premium_amount, Decimal):
            logger.error(f"Invalid ins_premium_amount: {self.ins_premium_amount}")
            raise ValueError("ins_premium_amount must be a Decimal")
        if not isinstance(self.ins_deductible, Decimal):
            logger.error(f"Invalid ins_deductible: {self.ins_deductible}")
            raise ValueError("ins_deductible must be a Decimal")
        if not isinstance(self.ins_effective_date, str) or len(self.ins_effective_date) != 8:
            logger.error(f"Invalid ins_effective_date: {self.ins_effective_date}")
            raise ValueError("ins_effective_date must be a string of length 8")
        if not isinstance(self.ins_expiry_date, str) or len(self.ins_expiry_date) != 8:
            logger.error(f"Invalid ins_expiry_date: {self.ins_expiry_date}")
            raise ValueError("ins_expiry_date must be a string of length 8")
        if not isinstance(self.ins_status, str) or len(self.ins_status) != 1:
            logger.error(f"Invalid ins_status: {self.ins_status}")
            raise ValueError("ins_status must be a string of length 1")
        if not isinstance(self.ins_claims_count, int) or not (0 <= self.ins_claims_count <= 9999):
            logger.error(f"Invalid ins_claims_count: {self.ins_claims_count}")
            raise ValueError("ins_claims_count must be an int between 0 and 9999")
        if not isinstance(self.ins_total_claims, Decimal):
            logger.error(f"Invalid ins_total_claims: {self.ins_total_claims}")
            raise ValueError("ins_total_claims must be a Decimal")

        except ValueError as e:
            logger.error(f"Validation error: {e}")
            raise

@dataclass
class InvestmentRecordC1:
    """
    Represents an investment record in the investment_master file
    Attributes:
        inv_id (str): Investment identifier (PIC X(16))
        inv_cust_id (str): Customer identifier associated with the investment (PIC X(12))
        inv_type (str): Investment type (PIC X(2)), e.g., 'ST', 'BO', 'MF', 'ET', 'OP'
        inv_symbol (str): Investment symbol (PIC X(10))
        inv_quantity (Decimal): Investment quantity (PIC S9(11)V9(4) comp_3)
        inv_purchase_price (Decimal): Purchase price (PIC S9(9)V9(4) comp_3)
        inv_current_price (Decimal): Current price (PIC S9(9)V9(4) comp_3)
        inv_market_value (Decimal): Market value (PIC S9(15)V99 comp_3)
        inv_gain_loss (Decimal): Gain or loss (PIC S9(13)V99 comp_3)
        inv_purchase_date (str): Purchase date (PIC 9(8))
        inv_dividend_rate (Decimal): Dividend rate (PIC V9(6))
    """
    inv_id: str
    inv_cust_id: str
    inv_type: str
    inv_symbol: str
    inv_quantity: Decimal
    inv_purchase_price: Decimal
    inv_current_price: Decimal
    inv_market_value: Decimal
    inv_gain_loss: Decimal
    inv_purchase_date: str
    inv_dividend_rate: Decimal

    
def __post_init__(self):
    """TODO"""
    """
        Validates the fields of the InvestmentRecord dataclass
        Raises:
            ValueError: If any field fails validation
        """
    logger.info("Validating InvestmentRecordC1 instance.")
    try:
        if not isinstance(self.inv_id, str) or len(self.inv_id) > 16:
            logger.error(f"Invalid inv_id: {self.inv_id}")
            raise ValueError("inv_id must be a string of length <= 16")
        if not isinstance(self.inv_cust_id, str) or len(self.inv_cust_id) > 12:
            logger.error(f"Invalid inv_cust_id: {self.inv_cust_id}")
            raise ValueError("inv_cust_id must be a string of length <= 12")
        if not isinstance(self.inv_type, str) or len(self.inv_type) > 2:
            logger.error(f"Invalid inv_type: {self.inv_type}")
            raise ValueError("inv_type must be a string of length <= 2")
        if not isinstance(self.inv_symbol, str) or len(self.inv_symbol) > 10:
            logger.error(f"Invalid inv_symbol: {self.inv_symbol}")
            raise ValueError("inv_symbol must be a string of length <= 10")
        if not isinstance(self.inv_quantity, Decimal):
            logger.error(f"Invalid inv_quantity: {self.inv_quantity}")
            raise ValueError("inv_quantity must be a Decimal")
        if not isinstance(self.inv_purchase_price, Decimal):
            logger.error(f"Invalid inv_purchase_price: {self.inv_purchase_price}")
            raise ValueError("inv_purchase_price must be a Decimal")
        if not isinstance(self.inv_current_price, Decimal):
            logger.error(f"Invalid inv_current_price: {self.inv_current_price}")
            raise ValueError("inv_current_price must be a Decimal")
        if not isinstance(self.inv_market_value, Decimal):
            logger.error(f"Invalid inv_market_value: {self.inv_market_value}")
            raise ValueError("inv_market_value must be a Decimal")
        if not isinstance(self.inv_gain_loss, Decimal):
            logger.error(f"Invalid inv_gain_loss: {self.inv_gain_loss}")
            raise ValueError("inv_gain_loss must be a Decimal")
        if not isinstance(self.inv_purchase_date, str) or len(self.inv_purchase_date) != 8:
            logger.error(f"Invalid inv_purchase_date: {self.inv_purchase_date}")
            raise ValueError("inv_purchase_date must be a string of length 8")
        if not isinstance(self.inv_dividend_rate, Decimal):
            logger.error(f"Invalid inv_dividend_rate: {self.inv_dividend_rate}")
            raise ValueError("inv_dividend_rate must be a Decimal")

        except ValueError as e:
            logger.error(f"Validation error: {e}")
            raise

@dataclass
class TransactionRecordC1:
    """
    Represents a transaction record in the transaction_log file
    Attributes:
        tran_id (str): Transaction identifier (PIC X(20))
        tran_timestamp (str): Transaction timestamp (PIC X(26))
        tran_type (str): Transaction type (PIC X(3))
        tran_acct_from (str): Source account identifier (PIC X(16))
        tran_acct_to (str): Destination account identifier (PIC X(16))
        tran_amount (Decimal): Transaction amount (PIC S9(13)V99 comp_3)
        tran_status (str): Transaction status (PIC X(