'use client';
import Link from 'next/link';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-900 text-white">
      <header className="border-b border-slate-700">
        <nav className="max-w-4xl mx-auto px-6 py-4">
          <Link href="/" className="text-2xl font-bold text-blue-400">CodeSwitch</Link>
        </nav>
      </header>

      <main className="max-w-4xl mx-auto px-6 py-12 prose prose-invert prose-lg">
        <h1>Terms of Service</h1>
        <p className="text-slate-400">Last updated: January 2, 2025</p>

        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing or using CodeSwitch (&quot;the Service&quot;), you agree to be bound by these 
          Terms of Service. If you do not agree, do not use the Service.
        </p>

        <h2>2. Description of Service</h2>
        <p>
          CodeSwitch provides AI-powered COBOL-to-Python code migration services, including:
        </p>
        <ul>
          <li>Automated code translation</li>
          <li>Test suite generation</li>
          <li>Security vulnerability scanning</li>
          <li>Configuration extraction</li>
          <li>Migration planning tools</li>
        </ul>

        <h2>3. User Responsibilities</h2>
        <p>You agree to:</p>
        <ul>
          <li>Provide accurate account information</li>
          <li>Maintain the security of your account credentials</li>
          <li>Use the Service only for lawful purposes</li>
          <li>Not attempt to reverse-engineer or copy our technology</li>
          <li>Not exceed your plan&apos;s usage limits</li>
          <li>Ensure you have rights to any code you upload</li>
        </ul>

        <h2>4. Intellectual Property</h2>
        <h3>4.1 Your Code</h3>
        <p>
          You retain all rights to the COBOL source code you submit. We claim no ownership 
          over your input or the generated Python output.
        </p>
        <h3>4.2 Our Technology</h3>
        <p>
          CodeSwitch&apos;s algorithms, user interface, documentation, and underlying technology 
          remain our exclusive property protected by intellectual property laws.
        </p>

        <h2>5. Generated Output</h2>
        <p>
          The Python code generated by CodeSwitch is provided as a starting point for migration. 
          <strong> You are responsible for reviewing, testing, and validating all generated code 
          before production use.</strong>
        </p>

        <h2>6. Disclaimer of Warranties</h2>
        <p>
          THE SERVICE IS PROVIDED &quot;AS IS&quot; WITHOUT WARRANTIES OF ANY KIND. WE DO NOT GUARANTEE:
        </p>
        <ul>
          <li>100% accuracy of code translations</li>
          <li>Functional equivalence between COBOL and generated Python</li>
          <li>Absence of bugs or security vulnerabilities in output</li>
          <li>Uninterrupted or error-free service availability</li>
        </ul>

        <h2>7. Limitation of Liability</h2>
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, CODESWITCH SHALL NOT BE LIABLE FOR:
        </p>
        <ul>
          <li>Indirect, incidental, or consequential damages</li>
          <li>Loss of profits, data, or business opportunities</li>
          <li>Damages arising from use of generated code in production</li>
          <li>Service interruptions or data loss</li>
        </ul>
        <p>
          Our total liability shall not exceed the amount paid by you in the 12 months 
          preceding the claim.
        </p>

        <h2>8. Payment Terms</h2>
        <ul>
          <li>Paid plans are billed monthly or annually in advance</li>
          <li>Prices are subject to change with 30 days notice</li>
          <li>Refunds are provided pro-rata for annual plans upon request</li>
          <li>Unpaid accounts may be suspended after 14 days</li>
        </ul>

        <h2>9. Termination</h2>
        <p>
          Either party may terminate this agreement at any time. Upon termination:
        </p>
        <ul>
          <li>Your access to the Service will be revoked</li>
          <li>Account data will be deleted within 30 days</li>
          <li>No refunds for partial months on monthly plans</li>
        </ul>

        <h2>10. Modifications</h2>
        <p>
          We reserve the right to modify these Terms at any time. Continued use of the 
          Service after changes constitutes acceptance of the new Terms.
        </p>

        <h2>11. Governing Law</h2>
        <p>
          These Terms are governed by the laws of the State of Delaware, USA, without 
          regard to conflict of law principles.
        </p>

        <h2>12. Contact</h2>
        <p>
          For questions about these Terms, contact us at:<br />
          <a href="mailto:legal@codeswitch.io" className="text-blue-400">legal@codeswitch.io</a>
        </p>

        <div className="mt-12 pt-8 border-t border-slate-700">
          <Link href="/" className="text-blue-400 hover:underline">&larr; Back to CodeSwitch</Link>
        </div>
      </main>
    </div>
  );
}
