import { NextRequest, NextResponse } from 'next/server';
import { GoogleGenerativeAI } from '@google/generative-ai';
import { parseCobolWithANTLR, generateANTLRSummary, CobolFullAST } from '@/lib/cobol-antlr-parser';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
};

const GEMINI_API_KEY = process.env.GEMINI_API_KEY || '';

const GEMINI_PROMPT = `You are CodeSwitch Pro, an expert COBOL-to-Python migration architect.

I will provide you with a COBOL AST (Abstract Syntax Tree) analysis generated by an ANTLR4 parser with full COBOL85 grammar.

**CRITICAL: Generate COMPLETE, FULL Python code that translates ALL COBOL logic.**
Do NOT summarize or skip any business logic. Every paragraph, every calculation, every condition must be translated.

REQUIREMENTS:
1. **COMPLETE TRANSLATION**: Translate EVERY paragraph in PROCEDURE DIVISION to a Python method
2. **ALL VARIABLES**: Create Python equivalents for ALL working storage variables
3. **FULL LOGIC**: Implement ALL PERFORM, IF, EVALUATE, COMPUTE, MOVE statements
4. Use @dataclass for all COBOL record structures
5. Use Decimal for all numeric PIC 9 with V (decimal) fields
6. Use complete type hints (typing module)
7. Include comprehensive docstrings referencing original COBOL line numbers
8. Generate pytest unit tests for EACH method
9. Handle PERFORM logic as method calls with proper control flow
10. Handle EVALUATE as match/case (Python 3.10+)
11. Handle embedded SQL with SQLAlchemy if present
12. Preserve ALL business logic - do not simplify or omit any calculations

Respond with ONLY a valid JSON object (no markdown, no code blocks, no explanation):
{
  "summary": "Brief description of what the program does",
  "business_context": {
    "domain": "Business domain (banking, insurance, payroll, etc.)",
    "detected_year": "Estimated year based on patterns",
    "regulatory_context": "Any compliance considerations",
    "is_obsolete": true/false,
    "obsolescence_reason": "Why if obsolete"
  },
  "python_code": "Complete Python code as a single string with actual newlines escaped as \\n",
  "unit_tests": "Complete pytest code as a single string with actual newlines escaped as \\n",
  "config_json": "Example configuration JSON string",
  "issues": ["List of issues found in the COBOL code"],
  "improvements": ["List of recommended improvements"],
  "security_warnings": [{"title": "Warning title", "severity": "HIGH/MEDIUM/LOW", "cvss_score": 5.0, "location": "Location", "description": "Description", "vulnerable_code": "Code", "fix": "Fix"}],
  "migration_score": {
    "complexity": "LOW/MEDIUM/HIGH",
    "risk_level": "LOW/MEDIUM/HIGH/CRITICAL",
    "estimated_effort": "X person-days",
    "confidence": 85
  },
  "architecture_diagram": "graph LR; A[Module] --> B[Class]",
  "next_steps": ["Step 1", "Step 2"]
}

COBOL AST Analysis:
`;

export async function OPTIONS() {
  return NextResponse.json({}, { headers: corsHeaders });
}

export async function POST(request: NextRequest) {
  const startTime = Date.now();
  
  try {
    const { cobolCode, filename } = await request.json();

    if (!cobolCode) {
      return NextResponse.json(
        { error: 'cobolCode is required' },
        { status: 400, headers: corsHeaders }
      );
    }

    if (!GEMINI_API_KEY) {
      return NextResponse.json(
        { error: 'GEMINI_API_KEY not configured' },
        { status: 500, headers: corsHeaders }
      );
    }

    // Parse COBOL with ANTLR4 (full COBOL85 grammar)
    console.log(`[AST] Parsing ${cobolCode.length} characters...`);
    const ast: CobolFullAST = parseCobolWithANTLR(cobolCode);
    console.log(`[AST] Parsed: ${ast.programId}, ${ast.metrics.variables} variables, ${ast.metrics.paragraphs} paragraphs`);
    
    // Generate AST summary for Gemini
    const astSummary = generateANTLRSummary(ast);
    console.log(`[AST] Summary generated: ${astSummary.length} characters`);

    // Call Gemini with AST
    const genAI = new GoogleGenerativeAI(GEMINI_API_KEY);
    const model = genAI.getGenerativeModel({ 
      model: 'gemini-2.0-flash',
      generationConfig: {
        responseMimeType: "application/json",
        maxOutputTokens: 65536, // Maximum output for complete code generation
      }
    });

    // Send BOTH AST summary AND actual COBOL code for complete translation
    const prompt = GEMINI_PROMPT + "\n\n=== AST ANALYSIS ===\n" + astSummary + "\n\n=== ORIGINAL COBOL CODE (translate ALL of this) ===\n" + cobolCode;
    console.log(`[Gemini] Calling API with ${prompt.length} character prompt (AST: ${astSummary.length}, Code: ${cobolCode.length}), maxTokens: 65536...`);
    
    const result = await model.generateContent(prompt);
    const response = await result.response;
    const text = response.text();
    console.log(`[Gemini] Response received: ${text.length} characters`);

    // Parse Gemini response - NO FALLBACK
    let parsed;
    try {
      parsed = JSON.parse(text);
    } catch (parseError) {
      console.error('[Gemini] JSON parse error:', text.substring(0, 500));
      throw new Error('Gemini returned invalid JSON. Response: ' + text.substring(0, 200));
    }

    // Enrich with AST metrics
    const finalResult = {
      ...parsed,
      cobol_lines: ast.metrics.totalLines,
      python_lines: (parsed.python_code || '').split(/\\n|\n/).length,
      _debug_gemini_response_length: text.length,
      filename: filename || `${ast.programId}.cbl`,
      confidence: parsed.migration_score?.confidence || 85,
      category: parsed.business_context?.domain || 'Enterprise Application',
      risk_level: parsed.migration_score?.risk_level || 'MEDIUM',
      complexity: parsed.migration_score?.complexity || 'MEDIUM',
      // AST-powered modules view
      modules: ast.paragraphs.map(p => ({
        name: p.name,
        lines: p.lineEnd - p.lineStart + 1,
        type: 'PARAGRAPH',
        description: `Lines ${p.lineStart}-${p.lineEnd}`,
        complexity: p.complexity > 3 ? 'HIGH' : p.complexity > 1 ? 'MEDIUM' : 'LOW',
      })),
      // Full AST metrics
      ast_metrics: ast.metrics,
      ast_parse_errors: ast.errors,
      ast_copybooks: ast.copyStatements,
      ast_sql_statements: ast.sqlStatements,
      ast_call_statements: ast.callStatements,
      ast_perform_statements: ast.performStatements.length,
      processing_time_ms: Date.now() - startTime,
    };

    console.log(`[Complete] Processed in ${finalResult.processing_time_ms}ms`);
    return NextResponse.json(finalResult, { headers: corsHeaders });

  } catch (error: any) {
    console.error('[Error]', error);
    return NextResponse.json(
      { error: error.message || 'Analysis failed' },
      { status: 500, headers: corsHeaders }
    );
  }
}
