import { NextRequest, NextResponse } from 'next/server';
import { GoogleGenerativeAI } from '@google/generative-ai';
import { parseCobolWithANTLR, generateANTLRSummary, CobolFullAST } from '@/lib/cobol-antlr-parser';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
};

const GEMINI_API_KEY = process.env.GEMINI_API_KEY || '';

const GEMINI_PROMPT = `You are CodeSwitch Pro, an expert COBOL-to-Python migration architect.

I will provide you with a COBOL AST (Abstract Syntax Tree) analysis generated by an ANTLR4 parser with full COBOL85 grammar.

**CRITICAL: Generate COMPLETE, FULL Python code that translates ALL COBOL logic.**
Do NOT summarize or skip any business logic. Every paragraph, every calculation, every condition must be translated.

REQUIREMENTS:
1. **COMPLETE TRANSLATION**: Translate EVERY paragraph in PROCEDURE DIVISION to a Python method
2. **ALL VARIABLES**: Create Python equivalents for ALL working storage variables
3. **FULL LOGIC**: Implement ALL PERFORM, IF, EVALUATE, COMPUTE, MOVE statements
4. Use @dataclass for all COBOL record structures
5. Use Decimal for all numeric PIC 9 with V (decimal) fields
6. Use complete type hints (typing module)
7. Include comprehensive docstrings referencing original COBOL line numbers
8. Generate pytest unit tests for EACH method
9. Handle PERFORM logic as method calls with proper control flow
10. Handle EVALUATE as match/case (Python 3.10+)
11. Handle embedded SQL with SQLAlchemy if present
12. Preserve ALL business logic - do not simplify or omit any calculations

Respond with ONLY a valid JSON object (no markdown, no code blocks, no explanation):
{
  "summary": "Brief description of what the program does",
  "business_context": {
    "domain": "Business domain (banking, insurance, payroll, etc.)",
    "detected_year": "Estimated year based on patterns",
    "regulatory_context": "Any compliance considerations",
    "is_obsolete": true/false,
    "obsolescence_reason": "Why if obsolete"
  },
  "python_code": "Complete Python code as a single string with actual newlines escaped as \\n",
  "unit_tests": "Complete pytest code as a single string with actual newlines escaped as \\n",
  "config_json": "Example configuration JSON string",
  "issues": ["List of issues found in the COBOL code"],
  "improvements": ["List of recommended improvements"],
  "security_warnings": [{"title": "Warning title", "severity": "HIGH/MEDIUM/LOW", "cvss_score": 5.0, "location": "Location", "description": "Description", "vulnerable_code": "Code", "fix": "Fix"}],
  "migration_score": {
    "complexity": "LOW/MEDIUM/HIGH",
    "risk_level": "LOW/MEDIUM/HIGH/CRITICAL",
    "estimated_effort": "X person-days",
    "confidence": 85
  },
  "architecture_diagram": "graph LR; A[Module] --> B[Class]",
  "next_steps": ["Step 1", "Step 2"]
}

COBOL AST Analysis:
`;

export async function OPTIONS() {
  return NextResponse.json({}, { headers: corsHeaders });
}

export async function POST(request: NextRequest) {
  const startTime = Date.now();
  
  try {
    const { cobolCode, filename } = await request.json();

    if (!cobolCode) {
      return NextResponse.json(
        { error: 'cobolCode is required' },
        { status: 400, headers: corsHeaders }
      );
    }

    if (!GEMINI_API_KEY) {
      return NextResponse.json(
        { error: 'GEMINI_API_KEY not configured' },
        { status: 500, headers: corsHeaders }
      );
    }

    // Parse COBOL with ANTLR4 (full COBOL85 grammar)
    console.log(`[AST] Parsing ${cobolCode.length} characters...`);
    const ast: CobolFullAST = parseCobolWithANTLR(cobolCode);
    console.log(`[AST] Parsed: ${ast.programId}, ${ast.metrics.variables} variables, ${ast.metrics.paragraphs} paragraphs`);
    
    // Generate AST summary for Gemini
    const astSummary = generateANTLRSummary(ast);
    console.log(`[AST] Summary generated: ${astSummary.length} characters`);

    // Call Gemini with AST
    const genAI = new GoogleGenerativeAI(GEMINI_API_KEY);
    const model = genAI.getGenerativeModel({ 
      model: 'gemini-2.0-flash',
      generationConfig: {
        responseMimeType: "application/json",
        maxOutputTokens: 65536, // Maximum output for complete code generation
      }
    });

    // Send BOTH AST summary AND actual COBOL code for complete translation
    const prompt = GEMINI_PROMPT + "\n\n=== AST ANALYSIS ===\n" + astSummary + "\n\n=== ORIGINAL COBOL CODE (translate ALL of this) ===\n" + cobolCode;
    console.log(`[Gemini] Calling API with ${prompt.length} character prompt (AST: ${astSummary.length}, Code: ${cobolCode.length}), maxTokens: 65536...`);
    
    const result = await model.generateContent(prompt);
    const response = await result.response;
    const text = response.text();
    console.log(`[Gemini] Response received: ${text.length} characters`);

    // Parse Gemini response
    let parsed;
    let usedFallback = false;
    try {
      parsed = JSON.parse(text);
    } catch (parseError) {
      console.error('[Gemini] JSON parse error, using fallback');
      parsed = generateFallbackFromAST(ast, filename);
      usedFallback = true;
    }

    // Enrich with AST metrics
    const finalResult = {
      ...parsed,
      cobol_lines: ast.metrics.totalLines,
      python_lines: (parsed.python_code || '').split(/\\n|\n/).length,
      _debug_used_fallback: usedFallback,
      _debug_gemini_response_length: text.length,
      filename: filename || `${ast.programId}.cbl`,
      confidence: parsed.migration_score?.confidence || 85,
      category: parsed.business_context?.domain || 'Enterprise Application',
      risk_level: parsed.migration_score?.risk_level || 'MEDIUM',
      complexity: parsed.migration_score?.complexity || 'MEDIUM',
      // AST-powered modules view
      modules: ast.paragraphs.map(p => ({
        name: p.name,
        lines: p.lineEnd - p.lineStart + 1,
        type: 'PARAGRAPH',
        description: `Lines ${p.lineStart}-${p.lineEnd}`,
        complexity: p.complexity > 3 ? 'HIGH' : p.complexity > 1 ? 'MEDIUM' : 'LOW',
      })),
      // Full AST metrics
      ast_metrics: ast.metrics,
      ast_parse_errors: ast.errors,
      ast_copybooks: ast.copyStatements,
      ast_sql_statements: ast.sqlStatements,
      ast_call_statements: ast.callStatements,
      ast_perform_statements: ast.performStatements.length,
      processing_time_ms: Date.now() - startTime,
    };

    console.log(`[Complete] Processed in ${finalResult.processing_time_ms}ms`);
    return NextResponse.json(finalResult, { headers: corsHeaders });

  } catch (error: any) {
    console.error('[Error]', error);
    return NextResponse.json(
      { error: error.message || 'Analysis failed' },
      { status: 500, headers: corsHeaders }
    );
  }
}

function generateFallbackFromAST(ast: CobolFullAST, filename?: string): any {
  const varDefs = ast.workingStorageVariables.slice(0, 15).map(v => {
    const pyType = v.picture?.includes('9') && v.picture?.includes('V') ? 'Decimal' : 
                   v.picture?.includes('9') ? 'int' : 'str';
    const pyDefault = pyType === 'Decimal' ? "Decimal('0')" : pyType === 'int' ? '0' : "''";
    return `    ${v.name.toLowerCase().replace(/-/g, '_')}: ${pyType} = ${pyDefault}`;
  }).join('\n');

  const methods = ast.paragraphs.slice(0, 10).map(p =>
    `    def ${p.name.toLowerCase().replace(/-/g, '_')}(self) -> None:\n        """${p.name} - Lines ${p.lineStart}-${p.lineEnd}"""\n        logger.info("Executing ${p.name}")\n        pass`
  ).join('\n\n');

  const className = ast.programId.replace(/-/g, '').replace(/[^A-Z0-9]/gi, '');

  const pythonCode = `"""
${ast.programId} - Migrated from COBOL using ANTLR4 AST Parser
Original: ${ast.metrics.totalLines} lines, ${ast.metrics.variables} variables, ${ast.metrics.paragraphs} paragraphs
Cyclomatic Complexity: ${ast.metrics.cyclomaticComplexity}
Maintainability Index: ${ast.metrics.maintainabilityIndex.toFixed(1)}
"""
from dataclasses import dataclass, field
from decimal import Decimal
from typing import Optional, List, Dict
import logging

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger('${ast.programId}')

@dataclass
class ${className}Data:
    """Working storage variables migrated from COBOL
    
    Original COBOL structure:
    - Level 01 variables: ${ast.metrics.level01Variables}
    - Total variables: ${ast.metrics.variables}
    """
${varDefs || '    value: Decimal = Decimal("0")'}

class ${className}:
    """Main program class - migrated from ${ast.programId}
    
    Migration Notes:
    - PERFORM statements: ${ast.metrics.performStatements}
    - CALL statements: ${ast.metrics.callStatements}
    - SQL statements: ${ast.metrics.sqlStatements}
    - GO TO statements: ${ast.metrics.gotoStatements} (requires refactoring)
    """
    
    def __init__(self) -> None:
        self.data = ${className}Data()
        logger.info(f"Initialized {self.__class__.__name__}")

${methods || '    def main(self) -> None:\n        """Main entry point"""\n        pass'}

    def run(self) -> None:
        """Execute the program - equivalent to PROCEDURE DIVISION entry"""
        logger.info(f"Starting {self.__class__.__name__}")
        try:
            self.main()
            logger.info(f"Completed {self.__class__.__name__} successfully")
        except Exception as e:
            logger.error(f"Error in {self.__class__.__name__}: {e}")
            raise

if __name__ == "__main__":
    program = ${className}()
    program.run()
`;

  const tests = `"""
Unit tests for ${ast.programId}
Generated from COBOL ANTLR4 AST analysis
"""
import pytest
from decimal import Decimal
from unittest.mock import patch, MagicMock
from main import ${className}Data, ${className}

class Test${className}Data:
    """Tests for data structure initialization"""
    
    def test_initialization(self) -> None:
        """Test default initialization"""
        data = ${className}Data()
        assert data is not None

    def test_decimal_precision(self) -> None:
        """Verify Decimal is used for financial calculations"""
        data = ${className}Data()
        # Check all numeric fields use Decimal
        for field_name, field_value in data.__dict__.items():
            if isinstance(field_value, (int, float)) and 'amount' in field_name.lower():
                pytest.fail(f"{field_name} should use Decimal, not {type(field_value)}")

class Test${className}:
    """Tests for main program logic"""
    
    def test_initialization(self) -> None:
        """Test program initialization"""
        program = ${className}()
        assert program.data is not None

    def test_run_completes(self) -> None:
        """Test that run() executes without error"""
        program = ${className}()
        program.run()  # Should not raise

    def test_logging(self) -> None:
        """Test that operations are logged"""
        with patch('main.logger') as mock_logger:
            program = ${className}()
            program.run()
            assert mock_logger.info.called

${ast.paragraphs.slice(0, 5).map(p => `    def test_${p.name.toLowerCase().replace(/-/g, '_')}(self) -> None:
        """Test ${p.name} paragraph logic"""
        program = ${className}()
        # TODO: Add specific assertions for ${p.name}
        assert hasattr(program, '${p.name.toLowerCase().replace(/-/g, '_')}')`).join('\n\n')}

class TestEdgeCases:
    """Edge case tests"""
    
    def test_empty_data(self) -> None:
        """Test handling of empty/default data"""
        data = ${className}Data()
        program = ${className}()
        program.run()

    def test_large_values(self) -> None:
        """Test handling of large numeric values"""
        data = ${className}Data()
        # COBOL typically supports up to PIC 9(18)
        # Ensure no overflow with large values
        pass
`;

  const issues = [
    ...ast.errors.map(e => `Parse error at line ${e.line}: ${e.message}`),
    ast.metrics.gotoStatements > 0 ? `${ast.metrics.gotoStatements} GO TO statements need refactoring to structured code` : null,
    ast.metrics.sqlStatements > 0 ? `${ast.metrics.sqlStatements} embedded SQL statements need migration to SQLAlchemy` : null,
    ast.copyStatements.length > 0 ? `${ast.copyStatements.length} COPY statements reference external copybooks: ${ast.copyStatements.join(', ')}` : null,
    ast.metrics.cyclomaticComplexity > 30 ? `High cyclomatic complexity (${ast.metrics.cyclomaticComplexity}) - consider breaking into smaller modules` : null,
    ast.metrics.maintainabilityIndex < 50 ? `Low maintainability index (${ast.metrics.maintainabilityIndex.toFixed(1)}) - code needs restructuring` : null,
  ].filter(Boolean);

  return {
    summary: `Migration of ${ast.programId}: ${ast.metrics.totalLines} lines COBOL → modern Python with ${ast.metrics.paragraphs} paragraphs`,
    business_context: {
      domain: ast.metrics.sqlStatements > 0 ? 'Database Application' : 
              ast.workingStorageVariables.some(v => v.name.includes('AMOUNT') || v.name.includes('RATE')) ? 'Financial Services' : 
              'Enterprise Application',
      detected_year: ast.metrics.gotoStatements > 5 ? '1970s-1980s' : '1990s-2000s',
      regulatory_context: ast.metrics.sqlStatements > 0 ? 'Data persistence and transaction processing' : 'Batch processing system',
      is_obsolete: true,
      obsolescence_reason: 'Legacy COBOL requires modernization for maintainability and cloud deployment',
    },
    python_code: pythonCode,
    unit_tests: tests,
    config_json: JSON.stringify({
      program: ast.programId,
      version: '1.0.0',
      migrated_from: 'COBOL85',
      logging_level: 'INFO',
      decimal_precision: 2,
      original_metrics: {
        lines: ast.metrics.totalLines,
        variables: ast.metrics.variables,
        paragraphs: ast.metrics.paragraphs,
        complexity: ast.metrics.cyclomaticComplexity,
      }
    }, null, 2),
    issues,
    improvements: [
      'Use Python dataclasses for type-safe data structures',
      'Implement proper exception handling with custom exceptions',
      'Add comprehensive logging with structured output',
      ast.metrics.sqlStatements > 0 ? 'Replace embedded SQL with SQLAlchemy ORM for database portability' : null,
      ast.metrics.gotoStatements > 0 ? 'Refactor GO TO statements to structured control flow' : null,
      'Add input validation and sanitization',
      'Implement unit tests with pytest (generated)',
      'Add type hints for better IDE support and static analysis',
      ast.copyStatements.length > 0 ? `Migrate copybooks to Python modules: ${ast.copyStatements.join(', ')}` : null,
    ].filter(Boolean),
    security_warnings: [
      ast.metrics.sqlStatements > 0 ? {
        title: 'SQL Injection Risk',
        severity: 'HIGH',
        cvss_score: 7.5,
        location: 'EXEC SQL statements',
        description: 'Dynamic SQL in COBOL may be vulnerable to injection attacks',
        vulnerable_code: 'EXEC SQL ... END-EXEC',
        fix: 'Use parameterized queries with SQLAlchemy',
      } : null,
      ast.workingStorageVariables.some(v => v.name.includes('PASSWORD') || v.name.includes('SECRET')) ? {
        title: 'Hardcoded Credentials',
        severity: 'CRITICAL',
        cvss_score: 9.0,
        location: 'WORKING-STORAGE SECTION',
        description: 'Possible hardcoded passwords or secrets in data definitions',
        vulnerable_code: 'PIC X fields with sensitive names',
        fix: 'Use environment variables or secure vault',
      } : null,
    ].filter(Boolean),
    migration_score: {
      complexity: ast.metrics.cyclomaticComplexity > 50 ? 'HIGH' : ast.metrics.cyclomaticComplexity > 20 ? 'MEDIUM' : 'LOW',
      risk_level: ast.metrics.gotoStatements > 10 ? 'HIGH' : ast.metrics.gotoStatements > 0 ? 'MEDIUM' : 'LOW',
      estimated_effort: `${Math.ceil(ast.metrics.totalLines / 80)}-${Math.ceil(ast.metrics.totalLines / 50)} person-days`,
      confidence: Math.max(50, 95 - (ast.metrics.gotoStatements * 3) - (ast.copyStatements.length * 5) - (ast.errors.length * 10)),
    },
    architecture_diagram: `graph LR
    subgraph COBOL[COBOL ${ast.programId}]
        A[IDENTIFICATION] --> B[DATA DIVISION]
        B --> C[PROCEDURE DIVISION]
    end
    subgraph Python[Python ${className}]
        D[${className}Data] --> E[${className}]
        E --> F[Unit Tests]
    end
    C --> E`,
    next_steps: [
      'Review generated Python code for business logic accuracy',
      ast.copyStatements.length > 0 ? `Migrate copybooks: ${ast.copyStatements.join(', ')}` : 'Verify data structure mappings',
      'Run generated unit tests and add business-specific assertions',
      'Validate numerical precision matches COBOL behavior',
      'Set up CI/CD pipeline for automated testing',
      'Deploy to staging environment for UAT',
    ],
  };
}
