// Supabase Edge Function for test generation
// This runs on Deno which has better cold start than Node.js

import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

serve(async (req) => {
  try {
    const { python_code, class_name } = await req.json()
    
    // Lightweight test generation - no AST parsing
    const tests = generate_simple_tests(python_code, class_name)
    
    return new Response(JSON.stringify({ tests }), {
      headers: { 'Content-Type': 'application/json' }
    })
  } catch (error) {
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' }
    })
  }
})

function generate_simple_tests(python_code: string, class_name: string): string {
  // Extract functions from code (simple regex-based, not AST)
  const functions = extract_functions(python_code)
  
  let tests = `"""
Tests for ${class_name}
Generated by Supabase Edge Function
"""

import pytest
from decimal import Decimal

`
  
  // Basic test class
  tests += `class Test${class_name}:
    """Basic tests for ${class_name}"""
    
    def test_decimal_precision(self):
        """Verify Decimal precision"""
        assert Decimal("0.1") + Decimal("0.2") == Decimal("0.3")
    
    def test_class_exists(self):
        """Verify class can be instantiated"""
        assert '${class_name}' is not None
`
  
  // Function-specific tests
  for (const func of functions.slice(0, 10)) {  // Limit to 10 functions
    tests += `
    def test_${func.name}_exists(self):
        """Test ${func.name} exists"""
        assert hasattr(self, '${func.name}')
        assert callable(self.${func.name})
`
  }
  
  return tests
}

function extract_functions(code: string): Array<{name: string, args: string[]}> {
  const functions = []
  const regex = /def\s+(\w+)\s*\(([^)]*)\)/g
  let match
  
  while ((match = regex.exec(code)) !== null && functions.length < 20) {
    const args = match[2].split(',').map((a: string) => a.trim()).filter((a: string) => a)
    functions.push({ name: match[1], args })
  }
  
  return functions
}
