"""
CodeSwitch v6.0.0 - New Features Module
Thread-safety, Equivalence Tests, External Call Templates
"""

import re
from typing import List, Dict, Any, Optional
from contextlib import contextmanager
from dataclasses import dataclass


class ThreadSafeWrapper:
    """v6.0.0: Wraps transpiled COBOL classes for thread-safe concurrent usage.
    
    Usage:
        wrapper = ThreadSafeWrapper(BankingSystem)
        result = wrapper.execute('run', data)  # Thread-safe
    """
    
    def __init__(self, cobol_class: type, config=None):
        self._cobol_class = cobol_class
        self._config = config
        self._lock = None
        
    def execute(self, method_name: str, *args, **kwargs) -> Any:
        """Execute a method on a fresh instance (thread-safe)."""
        instance = self._cobol_class()
        method = getattr(instance, method_name, None)
        if method is None:
            raise AttributeError(f"Method '{method_name}' not found")
        return method(*args, **kwargs)
    
    def execute_with_lock(self, method_name: str, *args, **kwargs) -> Any:
        """Execute with mutex lock for strict serialization."""
        import threading
        if self._lock is None:
            self._lock = threading.Lock()
        with self._lock:
            return self.execute(method_name, *args, **kwargs)


def wrap_thread_safe(cobol_class: type) -> ThreadSafeWrapper:
    """Create a thread-safe wrapper for a COBOL class."""
    return ThreadSafeWrapper(cobol_class)


def generate_external_call_template(call_names: List[str], output_path: str = 'core/external_calls.py') -> str:
    """Generate implementation templates for external COBOL CALLs.
    
    v6.0.0: Enhanced with user-friendly documentation and logging.
    """
    lines = [
        '"""',
        'External CALL Implementations for COBOL-transpiled code',
        'Generated by CodeSwitch v6.0.0',
        '',
        'INSTRUCTIONS:',
        '1. Implement each function below with your business logic',
        '2. Remove the NotImplementedError once implemented',
        '3. Set ALLOW_STUBS=false in production',
        '"""',
        '',
        'from typing import Any, Optional, Dict, List',
        'from decimal import Decimal',
        'from datetime import datetime',
        'import logging',
        'import os',
        '',
        'logger = logging.getLogger(__name__)',
        '',
        '# Track missing implementations at runtime',
        '_missing_calls_log: List[Dict] = []',
        '',
        '',
        'def _log_missing_call(method: str, cobol_call: str, args: tuple):',
        '    """Log a missing CALL for debugging and migration tracking."""',
        '    entry = {',
        '        "timestamp": datetime.now().isoformat(),',
        '        "method": method,',
        '        "cobol_call": cobol_call,',
        '        "args_count": len(args),',
        '    }',
        '    _missing_calls_log.append(entry)',
        '    logger.warning(f"MISSING IMPLEMENTATION: {cobol_call} -> {method}()")',
        '',
        '',
        'def get_missing_calls_report() -> List[Dict]:',
        '    """Get all missing CALL invocations for migration tracking."""',
        '    return _missing_calls_log.copy()',
        '',
    ]
    
    # Map CALL names to likely purposes for better documentation
    call_hints = {
        'AUTH': ('Authentication', 'Validate user credentials and return auth level'),
        'SESSION': ('Session Management', 'Create/validate user sessions'),
        'SECURITY': ('Security', 'Handle security alerts and violations'),
        'FRAUD': ('Fraud Detection', 'Check for fraud indicators in data'),
        'AUDIT': ('Audit Logging', 'Log actions for compliance/audit trail'),
        'METRIC': ('Metrics', 'Update business metrics and KPIs'),
        'ENCRYPT': ('Encryption', 'Encrypt/decrypt sensitive data'),
        'VALIDATE': ('Validation', 'Validate business data'),
        'CALC': ('Calculation', 'Perform business calculations'),
        'REPORT': ('Reporting', 'Generate reports'),
    }
    
    for call_name in call_names:
        func_name = "call_" + call_name.lower().replace('-', '_')
        
        # Find matching hint
        category, hint = 'Business Logic', 'Implement according to original COBOL specification'
        for key, (cat, h) in call_hints.items():
            if key in call_name.upper():
                category, hint = cat, h
                break
        
        lines.extend([
            '',
            f'def {func_name}(*args, **kwargs) -> int:',
            f'    """',
            f'    COBOL CALL: {call_name}',
            f'    Category: {category}',
            f'    ',
            f'    Purpose:',
            f'        {hint}',
            f'    ',
            f'    Implementation Steps:',
            f'        1. Review original COBOL CALL parameters',
            f'        2. Connect to your backend system ({category.lower()})',
            f'        3. Process the request and update output parameters',
            f'        4. Return 0 for success, non-zero for error',
            f'    ',
            f'    Args:',
            f'        *args: Parameters from COBOL USING clause',
            f'        **kwargs: Additional context',
            f'    ',
            f'    Returns:',
            f'        int: Return code (0=success, 4=warning, 8+=error)',
            f'    """',
            f'    _log_missing_call("{func_name}", "{call_name}", args)',
            f'    ',
            f'    # ============================================================',
            f'    # TODO: YOUR IMPLEMENTATION HERE',
            f'    # ============================================================',
            f'    #',
            f'    # Example implementation:',
            f'    #',
            f'    #     # Extract parameters',
            f'    #     user_id = args[0] if len(args) > 0 else None',
            f'    #     ',
            f'    #     # Call your backend',
            f'    #     result = your_backend.process(user_id)',
            f'    #     ',
            f'    #     # Return code',
            f'    #     return 0 if result.success else 8',
            f'    #',
            f'    # ============================================================',
            f'    ',
            f'    if os.getenv("ALLOW_STUBS", "") == "true":',
            f'        logger.info(f"STUB: {call_name} called with {{len(args)}} args")',
            f'        return 0  # Stub success',
            f'    ',
            f'    raise NotImplementedError(',
            f'        f"\\n"',
            f'        f"╔══════════════════════════════════════════════════════════╗\\n"',
            f'        f"║  EXTERNAL CALL NOT IMPLEMENTED: {call_name:<24} ║\\n"',
            f'        f"╠══════════════════════════════════════════════════════════╣\\n"',
            f'        f"║  Category: {category:<45} ║\\n"',
            f'        f"║  Function: {func_name:<45} ║\\n"',
            f'        f"╠══════════════════════════════════════════════════════════╣\\n"',
            f'        f"║  To fix:                                                 ║\\n"',
            f'        f"║  1) Implement {func_name}() in this file    ║\\n"',
            f'        f"║  2) Or set ALLOW_STUBS=true (dev only)                   ║\\n"',
            f'        f"╚══════════════════════════════════════════════════════════╝"',
            f'    )',
            '',
        ])
    
    # Module exports
    all_funcs = ["call_" + n.lower().replace('-', '_') for n in call_names]
    all_funcs.extend(['get_missing_calls_report', '_log_missing_call'])
    lines.extend([
        '',
        f'__all__ = {all_funcs}',
    ])
    
    return '\n'.join(lines)


def generate_equivalence_tests(cobol_source: str, python_class_name: str) -> str:
    """Generate equivalence tests to verify COBOL-Python parity."""
    
    # Extract program ID
    match = re.search(r'PROGRAM-ID\.\s*(\S+)', cobol_source, re.IGNORECASE)
    program_id = match.group(1).rstrip('.') if match else 'UNKNOWN'
    class_lower = python_class_name.lower()
    
    lines = [
        '"""',
        f'Equivalence Tests for {program_id}',
        'Generated by CodeSwitch v6.0.0',
        '"""',
        '',
        'import pytest',
        'from decimal import Decimal',
        '',
        '',
        f'class TestEquivalence{python_class_name}:',
        f'    """Equivalence tests for {python_class_name}."""',
        '    ',
        '    @pytest.fixture',
        '    def system(self):',
        '        """Create fresh instance for each test."""',
        f'        from output.{class_lower} import {python_class_name}',
        f'        return {python_class_name}()',
        '    ',
        '    def test_initialization_defaults(self, system):',
        '        """Verify fields initialize to COBOL-compatible defaults."""',
        '        for attr_name in dir(system):',
        '            if attr_name.startswith("_"):',
        '                continue',
        '            attr = getattr(system, attr_name)',
        '            if isinstance(attr, Decimal):',
        '                assert attr >= Decimal("0"), f"{attr_name} should be >= 0"',
        '    ',
        '    def test_88_level_conditions(self, system):',
        '        """Verify 88-level condition properties work correctly."""',
        '        for attr_name in dir(system.__class__):',
        '            prop = getattr(system.__class__, attr_name, None)',
        '            if isinstance(prop, property):',
        '                try:',
        '                    result = getattr(system, attr_name)',
        '                    assert isinstance(result, bool)',
        '                except Exception:',
        '                    pass',
        '',
        '',
        'class TestRegressionSuite:',
        '    """Regression tests with known COBOL input/output pairs."""',
        '    ',
        '    @pytest.fixture',
        '    def golden_cases(self):',
        '        """Load golden test cases from COBOL runs."""',
        '        return []  # TODO: Add test cases',
        '    ',
        '    def test_golden_cases(self, golden_cases):',
        '        """Run all golden test cases."""',
        f'        from output.{class_lower} import {python_class_name}',
        '        for case in golden_cases:',
        f'            system = {python_class_name}()',
        '            for k, v in case.get("input", {}).items():',
        '                setattr(system, k, v)',
        '            system.run()',
        '            for k, expected in case.get("expected", {}).items():',
        '                assert getattr(system, k) == expected',
    ]
    
    return '\n'.join(lines)


class RedefinesSimulator:
    """v6.0.0: Simulates COBOL REDEFINES memory overlay behavior."""
    
    def __init__(self):
        self._memory: Dict[str, bytes] = {}
        self._layouts: Dict[str, List[tuple]] = {}
    
    def define_layout(self, base_name: str, *fields):
        """Define a REDEFINES layout."""
        self._layouts[base_name] = list(fields)
    
    def set_base(self, base_name: str, value: str):
        """Set the base field value."""
        self._memory[base_name] = value.encode('latin-1')
    
    def get_field(self, base_name: str, field_name: str) -> str:
        """Get a redefined field's value."""
        if base_name not in self._layouts:
            return ''
        for name, offset, length in self._layouts[base_name]:
            if name == field_name:
                data = self._memory.get(base_name, b'')
                return data[offset:offset+length].decode('latin-1')
        return ''


# ============================================================
# v6.0.0: Enhanced User Experience Features
# ============================================================

def generate_run_with_guidance_method(external_calls: List[str]) -> str:
    """Generate run_with_guidance() method for better first-run experience."""
    calls_list = ', '.join(f'"{c}"' for c in external_calls)
    
    return f'''
    def run_with_guidance(self, ls_control_block: 'Optional[Dict[str, Any]]'=None, 
                          ls_data_block: 'Optional[Dict[str, Any]]'=None):
        """Enhanced entry point with guidance for missing implementations.
        
        v6.0.0: Provides helpful feedback instead of cryptic errors.
        """
        import os
        missing_methods = [{calls_list}]
        
        if os.getenv('ALLOW_STUBS', '') != 'true' and missing_methods:
            print("=" * 60)
            print("⚠️  CODESWITCH MIGRATION ASSISTANT")
            print("=" * 60)
            print(f"\\n{{len(missing_methods)}} external CALL(s) need implementation:\\n")
            for m in missing_methods:
                print(f"  • {{m}}")
            print("\\nOptions:")
            print("  1) Set ALLOW_STUBS=true to run with stubs (dev only)")
            print("  2) Implement methods in core/external_calls.py")
            print("  3) See generated template: core_external_calls_template.py")
            print("=" * 60)
            return {{"status": "guidance", "missing": missing_methods}}
        
        return self.run(ls_control_block, ls_data_block)
'''


def generate_migration_report(cobol_source: str, python_class_name: str, 
                              external_calls: List[str], stats: Dict) -> str:
    """Generate a migration report with business metrics."""
    import re
    
    # Count COBOL elements
    perform_count = len(re.findall(r'\bPERFORM\b', cobol_source, re.IGNORECASE))
    compute_count = len(re.findall(r'\bCOMPUTE\b', cobol_source, re.IGNORECASE))
    call_count = len(re.findall(r'\bCALL\b', cobol_source, re.IGNORECASE))
    lines_cobol = len(cobol_source.splitlines())
    
    report = f'''# Migration Report: {python_class_name}
Generated by CodeSwitch v6.0.0

## Summary
| Metric | Value |
|--------|-------|
| COBOL Lines | {lines_cobol} |
| Python Methods Generated | {stats.get('total_methods', 'N/A')} |
| External CALLs to Implement | {len(external_calls)} |
| PERFORM Statements | {perform_count} |
| COMPUTE Statements | {compute_count} |

## External Dependencies
{chr(10).join(f'- [ ] `{c}` - Requires implementation' for c in external_calls) if external_calls else '- None detected ✅'}

## Risk Assessment
- **Low Risk**: Architecture, data types, control flow
- **Medium Risk**: External CALLs ({len(external_calls)} to implement)
- **Verify**: File I/O paths, date/time handling

## Next Steps
1. Review generated Python code
2. Implement external CALLs (see `core_external_calls_template.py`)
3. Run equivalence tests with production data samples
4. Deploy with `ALLOW_STUBS=false` (production mode)
'''
    return report


@dataclass
class MigrationMetrics:
    """v6.0.0: Metrics for migration tracking."""
    cobol_lines: int = 0
    python_methods: int = 0
    external_calls: int = 0
    complexity_score: int = 0
    risk_level: str = "LOW"
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "cobol_lines": self.cobol_lines,
            "python_methods": self.python_methods,
            "external_calls": self.external_calls,
            "complexity_score": self.complexity_score,
            "risk_level": self.risk_level
        }
